### ISSUE TITLE
Input buffer overrun.

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#1]
Input buffer overrun. Scanner, generated by re2c reads
one byte after the end of input buffer.

This bug taken from
http://ufo2000.lxnt.info/pmwiki/index.php/Re2c/Bugs

test.re:

#include &lt;stdio.h&gt;
#include &lt;string.h&gt;

#define    YYCTYPE        char
#define    YYCURSOR    cursor
#define    YYLIMIT        cursor
#define    YYMARKER    marker
#define    YYFILL(n)

int test(const char *text)
{
YYCTYPE *cursor = (YYCTYPE *)text;
YYCTYPE *marker = (YYCTYPE *)text;
next:;
YYCTYPE *token = cursor;
/*!re2c
[\001-\377]        { return 0; }
[\000]             { return 1; }
*/
}

int main()
{
char *text = new char[1];
strcpy(text, "");
test(text);
}

test.cpp:

/* Generated by re2c 0.5 on Thu Nov  6 13:57:12 2003 */
#line 1 "test.re"
#include &lt;stdio.h&gt;
#include &lt;string.h&gt;

#define    YYCTYPE        char
#define    YYCURSOR    cursor
#define    YYLIMIT        cursor
#define    YYMARKER    marker
#define    YYFILL(n)

int test(const char *text)
{
YYCTYPE *cursor = (YYCTYPE *)text;
YYCTYPE *marker = (YYCTYPE *)text;
next:;
YYCTYPE *token = cursor;
{
YYCTYPE yych;
unsigned int yyaccept;
goto yy0;
yy1:    ++YYCURSOR;
yy0:
if(YYLIMIT == YYCURSOR) YYFILL(1);
yych = *YYCURSOR;
if(yych &lt;= '\000')    goto yy4;
yy2:    yych = *++YYCURSOR;
yy3:
#line 17
{ return 0; }
yy4:    yych = *++YYCURSOR;
yy5:
#line 18
{ return 1; }
}
#line 19

}

int main()
{
char *text = new char[1];
strcpy(text, "");
test(text);
}

valgrind.log:

==1781== Memcheck, a.k.a. Valgrind, a memory error
detector for x86-linux.
==1781== Copyright (C) 2002, and GNU GPL'd, by Julian
Seward.
==1781== Using valgrind-1.9.6, a program
instrumentation system for x86-linux.
==1781== Copyright (C) 2000-2002, and GNU GPL'd, by
Julian Seward.
==1781== Estimated CPU clock rate is 962 MHz
==1781== For more details, rerun with: -v
==1781==
==1781== Invalid read of size 1
==1781==    at 0x80484B0: test(char const*) (in
/home/serge/test/test)
==1781==    by 0x80484FE: main (in /home/serge/test/test)
==1781==    by 0x403077A6: __libc_start_main (in
/lib/libc-2.3.2.so)
==1781==    by 0x80483D0: (within /home/serge/test/test)
==1781==    Address 0x41116059 is 0 bytes after a block
of size 1 alloc'd
==1781==    at 0x40161948: __builtin_vec_new (in
/usr/lib/valgrind/valgrind.so)
==1781==    by 0x40161990: operator new[](unsigned) (in
/usr/lib/valgrind/valgrind.so)
==1781==    by 0x80484DD: main (in /home/serge/test/test)
==1781==    by 0x403077A6: __libc_start_main (in
/lib/libc-2.3.2.so)
==1781==
==1781== ERROR SUMMARY: 1 errors from 1 contexts
(suppressed: 0 from 0)
==1781== malloc/free: in use at exit: 1 bytes in 1 blocks.
==1781== malloc/free: 2 allocs, 1 frees, 3 bytes allocated.
==1781== For a detailed leak analysis,  rerun with:
--leak-check=yes
==1781== For counts of detected errors, rerun with: -v

Original comment by: nuffer

**Comment by linuxlovell** [comment]
thanks www.movied.org
