### ISSUE TITLE
Support to configure how re2c code interfaced with the symbol buffer?

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#109]
It would be great if re2c could be configured to interface with the parser buffer through interfaces other than dereferencing pointers to an array.

Currently, re2c assumes that the buffer is a C array and is operated directly through pointers to it.  Consequently, YYCURSOR is assumed to be an l-value of type * YYCTYPE.  Therefore, re2c generates code to access the current symbol and next symbol, respectively, as:

yych = *YYCURSOR;
yych = *++YYCURSOR;

If re2c is used to help write a lexer in C++, the symbol buffer can be managed directly by an std::ifstream object, which also provides the relevant interfaces.   The same operations mentioned above could be performed through the following calls:

yych = ifstream_object.peek();
yych = ifstream_object.get();

Would it be possible to offer a way to define how re2c would generate the code that handled access the current and next symbol in the buffer?  Something similar to the following code:

re2c:define:define:ACCESS_CURRENT_SYMBOL = yych = *YYCURSOR;
re2c:define:define:ACCESS_NEXT_SYMBOL = yych = *++YYCURSOR;
re2c:define:define:MOVE_TO_NEXT_SYMBOL = ++YYCURSOR;

Original comment by: rui_maciel

**Comment by ruimaciel** [comment]
Is this feature already supported by re2c?  I've browsed through the site but I failed to find anything regarding re2c supporting calls to istream.

**Comment by skvadrik** [comment]
Sure, we added generic API about a year ago in 0.14 release. It is documented on re2c.org: http://re2c.org/manual/features/generic_api/generic_api.html, and it appeared in changelog http://re2c.org/news/changelog/changelog.html#id11. These docs should be updated and included into the official manual, I will probably get to it soon.

A more detailed documentation is here: http://skvadrik.github.io/aleph_null/posts/re2c/2015-01-15-input_model_custom.html (a couple of examples) and http://skvadrik.github.io/aleph_null/posts/re2c/2015-01-13-input_model.html (an overview of re2c input model and some reasoning why we have generic API in the form we have it now).

There were reports of people successfully using it, and you can also find lots of examples in re2c test suite (pick those with `--input(custom)` in file name).

**Comment by ruimaciel** [comment]
I have to say, what a tremendous job.  I particularly enjoyed reading [this article](http://skvadrik.github.io/aleph_null/posts/re2c/2015-01-14-input_model_assembly.html).  I also noticed that I was mentioned in the acknowledgements section of [this article](http://skvadrik.github.io/aleph_null/posts/re2c/2015-01-13-input_model.html).  How cool is that?

Keep up the good work.

**Comment by skvadrik** [comment]
Glad you liked it, and thanks for the motivation!
