### ISSUE TITLE
documentation for default case handling

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#117]
As of now, I can think of at least three flavours of "defailt rule" in re2c:
- old default rule `[^]`, which means "match any _code point_", consumes one or more code units (depending on encoding) and has normal priority;
- new default rule `*`, which means "match any _code unit_" , consumes exactly one code unit and has the lowest priority;
- empty string rule `""` (as well as, `'`', `"" / ""` , etc.), which means "match empty string", consumes no code units and has normal priority;

They should be well-documented to avoid confusion.

**Comment by sergeyklay** [comment]
Hello @skvadrik 

It is mostly question but not a real issue; Should I always use **`*`** for the default rule or **`[^]`** more safer in term of portability? Unfortunately, I don’t have any statistics, so I can’t deal how much popular re2c <= 0.13.7. I personally use 1.1.1 (on my laptop). But for example PHP uses 0.13.4 https://github.com/php/php-src/blob/4dd7177224140ceb042b1271c25340447fe6f9ce/acinclude.m4#L2091-L2095.

Another question is: Is there any hack to determine re2c version to choice the right pattern for the default rule (and any good reason to do that)?

And finally: could you please provide a small real-world example which will show the real difference in the result of using these default rules.

Thank you

**Comment by skvadrik** [comment]
Hi @sergeyklay,

> Should I always use * for the default rule or [^] more safer in term of portability?

The usual way to resolve portability issue is to bundle pre-generated files together with other sources, and check during configuration if re2c is available or not. You can do autoconf-style feature detection: check if re2c can compile a small program containing default rule. If the test fails, fall back to pre-generated files. Then it's only developers who need a fresh enough re2c (in fact, only those of them who change re2c files) --- users can have no re2c at all.

> Unfortunately, I don’t have any statistics

Looking at https://repology.org/metapackage/re2c/versions, I see that most distros have updated to at least 16.0, and many to even 1.1.1. The "oldstable" ones still have 0.13.5, but that makes sense. So it seems reasonable to assume version greater than 0.13.7. Also, you can run repology on your own if you need to automate version lookup: https://github.com/repology/repology/blob/master/docs/RUNNING.md.

> But for example PHP uses 0.13.4

They use *at least* 0.13.4, and that usually means, whatever the distribution provides. On gentoo it often was, if the new re2c release breaks, php team are the first to notice. :)

> Another question is: Is there any hack to determine re2c version to choice the right pattern for the default rule (and any good reason to do that)?

You can either do a version check (run `re2c --version` and compare it to `0.13.7`), or you can do feature-detect check (run something like `echo '/*!re2c * {} */' | re2c - >/dev/null 2>&1 && echo yes || echo no`). Both of the above can be used at configuration time to patch .re files. But that would be very fragile: default rule is special, and just substituting `*` for `[^]` and vice versa may break the code in subtle ways (`*` has the lowest priority regardless of rule order, unlike `[^]`; it is possible to have many `[^]` rules, but only one `*`; etc.). If supporting re2c versions less than 0.13.7 is a requirement, I would just use `[^]` (variable-lenght encodings weren't supported before 0.13.7 anyway, so `*` won't be of much use).

> And finally: could you please provide a small real-world example which will show the real difference in the result of using these default rules.

Sure. Default rule is really necessary with encodings in which some sequences of *code units* do not map to any *code point*. That is, it is possible to have input which is not encoded correctly. Of the re2c-supported encodings, this happens with UTF-8. If we try compiling `[^]` with `-8` option, re2c will give a warning that some of the paths in lexer lead to undefined behaviour:
```
$ echo '/*!re2c [^] {} */' | ./re2c - -8 -W >/dev/null
re2c: warning: line 1: control flow is undefined for strings that match 
        '[\x80-\xC1\xF5-\xFF]'
        '[\xC2-\xDF] [\x0-\x7F\xC0-\xFF]'
        '\xE0 [\x0-\x9F\xC0-\xFF]'
        '[\xE1-\xEF] [\x0-\x7F\xC0-\xFF]'
        '\xF0 [\x0-\x8F\xC0-\xFF]'
        '[\xF1-\xF3] [\x0-\x7F\xC0-\xFF]'
        '\xF4 [\x0-\x7F\x90-\xFF]'
        '\xE0 [\xA0-\xBF] [\x0-\x7F\xC0-\xFF]'
        '[\xE1-\xEF] [\x80-\xBF] [\x0-\x7F\xC0-\xFF]'
        '\xF0 [\x90-\xBF] [\x0-\x7F\xC0-\xFF]'
        '[\xF1-\xF3] [\x80-\xBF] [\x0-\x7F\xC0-\xFF]'
        '\xF4 [\x80-\x8F] [\x0-\x7F\xC0-\xFF]'
        '\xF0 [\x90-\xBF] [\x80-\xBF] [\x0-\x7F\xC0-\xFF]'
        '[\xF1-\xF3] [\x80-\xBF] [\x80-\xBF] [\x0-\x7F\xC0-\xFF]'
        '\xF4 [\x80-\x8F] [\x80-\xBF] [\x0-\x7F\xC0-\xFF]'
, use default rule '*' [-Wundefined-control-flow]
```
To make sure this indeed happens, we can run re2c self-validation: `-S` option.  It will generate a self-contained program `1.c` and two input binary files `1.c.line1.input` (input strings) and `1.c.line1.keys` (expected match results). If we compile and run `1.c`, it will detect the first input string for which lexer match results differ from the expected results:
```
$ echo '/*!re2c [^] {} */' | ./re2c - -8 -S -o 1.c && gcc 1.c -o 1 && ./1
warning: lex_line1: control flow is undefined for input at position 256, rerun re2c with '-W'
error: lex_line1: at position 256 (key 576):
        expected: match length 0, rule 255
        actual:   match length 2, rule 0
```
If we look into the generated files, we'll see that at offset `256` in `1.c.line1.input` there is a string starting with `C2 80`, mentioned in the warning given by re2c (invalid sequences from other ranges occur later in the file). `C2 80` doesn't map to any valid code point in UTF-8, therefore it is not captured by `[^]` rule and not handled properly by the lexer. The warning and the error are fixed if we use default rule:
```
$ echo '/*!re2c * {} */' | ./re2c - -8 -S -W -o 1.c && gcc 1.c -o 1 && ./1
$
```
This example is not real-world, but it can be made real-world by adding any number of rules: the only way to handle faulty paths is to use the `*` rule.

**Comment by sergeyklay** [comment]
Thank you for the clarification!

**Comment by sergeyklay** [comment]
IMO you definitely should add this to the docs :)

**Comment by skvadrik** [comment]
I wrote some a while ago, but it's very well hidden: http://re2c.org/manual/warnings/undefined_control_flow/wundefined_control_flow.html#difference-between-and. Self-validation is also documented, but in a different part of the manual: http://re2c.org/manual/features/skeleton/skeleton.html#undefined-control-flow. Some day I'll get to writing a short tutorial with all useful links in one page.
