### ISSUE TITLE
[-Weffc++] false positives on centos 7 with gcc 4.8.3

### ISSUE THREAD

**Issue by mia0x75** [skvadrik/re2c#126]
Can these warnings be fixed in the coming release? thx
# make

make  all-am
make[1]: Entering directory `/opt/download/re2c-0.15.3'
  CXX      src/codegen/bitmap.o
  CXX      src/codegen/emit_action.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from ./src/codegen/emit.h:5,
                 from src/codegen/emit_action.cc:6:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/codegen/emit_dfa.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from ./src/codegen/emit.h:5,
                 from src/codegen/emit_dfa.cc:9:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/codegen/label.o
  CXX      src/codegen/prepare_dfa.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from src/codegen/prepare_dfa.cc:11:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/codegen/go_construct.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/state.h:6,
                 from src/codegen/go_construct.cc:10:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/codegen/go_destruct.o
  CXX      src/codegen/go_emit.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/state.h:6,
                 from src/codegen/go_emit.cc:14:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/codegen/go_used_labels.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/state.h:6,
                 from src/codegen/go_used_labels.cc:8:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/codegen/input_api.o
  CXX      src/codegen/output.o
  CXX      src/codegen/print.o
  CXX      src/codegen/scc.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/state.h:6,
                 from src/codegen/scc.cc:3:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/codegen/skeleton/control_flow.o
  CXX      src/codegen/skeleton/generate_code.o
  CXX      src/codegen/skeleton/generate_data.o
  CXX      src/codegen/skeleton/match_empty.o
  CXX      src/codegen/skeleton/maxlen.o
  CXX      src/codegen/skeleton/skeleton.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from src/codegen/skeleton/skeleton.cc:8:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/codegen/skeleton/unreachable.o
  CXX      src/codegen/skeleton/way.o
  CXX      src/conf/msg.o
  CXX      src/conf/opt.o
  CXX      src/conf/warn.o
  CXX      src/ir/bytecode/bytecode.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from src/ir/bytecode/bytecode.cc:8:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/bytecode/ins.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/regexp/regexp_rule.h:6,
                 from src/ir/bytecode/ins.cc:4:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/bytecode/charset.o
  CXX      src/ir/bytecode/split.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from src/ir/bytecode/split.cc:4:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/bytecode/compile.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from src/ir/bytecode/compile.cc:4:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/bytecode/calc_size.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from src/ir/bytecode/calc_size.cc:3:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/dfa/dfa.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from src/ir/dfa/dfa.cc:7:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/regexp/display.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from src/ir/regexp/display.cc:3:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/regexp/encoding/enc.o
In file included from ./src/util/range.h:10:0,
                 from src/ir/regexp/encoding/enc.cc:2:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/ir/regexp/encoding/range_suffix.o
In file included from ./src/ir/regexp/encoding/range_suffix.h:8:0,
                 from src/ir/regexp/encoding/range_suffix.cc:1:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RangeSuffix*>’:
./src/ir/regexp/encoding/range_suffix.h:29:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RangeSuffix*, std::less<re2c::RangeSuffix*>, std::allocator<re2c::RangeSuffix*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/regexp/encoding/utf8/utf8_regexp.o
In file included from ./src/ir/regexp/encoding/range_suffix.h:8:0,
                 from src/ir/regexp/encoding/utf8/utf8_regexp.cc:4:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RangeSuffix*>’:
./src/ir/regexp/encoding/range_suffix.h:29:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RangeSuffix*, std::less<re2c::RangeSuffix*>, std::allocator<re2c::RangeSuffix*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/regexp/encoding/utf8/utf8_range.o
In file included from ./src/ir/regexp/encoding/range_suffix.h:8:0,
                 from src/ir/regexp/encoding/utf8/utf8_range.cc:2:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RangeSuffix*>’:
./src/ir/regexp/encoding/range_suffix.h:29:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RangeSuffix*, std::less<re2c::RangeSuffix*>, std::allocator<re2c::RangeSuffix*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/ir/regexp/encoding/utf8/utf8.o
  CXX      src/ir/regexp/encoding/utf16/utf16_regexp.o
In file included from ./src/ir/regexp/encoding/range_suffix.h:8:0,
                 from src/ir/regexp/encoding/utf16/utf16_regexp.cc:4:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RangeSuffix*>’:
./src/ir/regexp/encoding/range_suffix.h:29:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RangeSuffix*, std::less<re2c::RangeSuffix*>, std::allocator<re2c::RangeSuffix*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/regexp/encoding/utf16/utf16.o
  CXX      src/ir/regexp/encoding/utf16/utf16_range.o
In file included from ./src/ir/regexp/encoding/range_suffix.h:8:0,
                 from src/ir/regexp/encoding/utf16/utf16_range.cc:2:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RangeSuffix*>’:
./src/ir/regexp/encoding/range_suffix.h:29:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RangeSuffix*, std::less<re2c::RangeSuffix*>, std::allocator<re2c::RangeSuffix*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/ir/regexp/fixed_length.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from src/ir/regexp/fixed_length.cc:3:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
  CXX      src/ir/regexp/regexp.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from src/ir/regexp/regexp.cc:9:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
In file included from src/ir/regexp/regexp.cc:15:0:
./src/parse/scanner.h:52:7: warning: base class ‘struct re2c::ScannerState’ has a non-virtual destructor [-Weffc++]
 class Scanner: private ScannerState
       ^
  CXX      src/ir/rule_rank.o
  CXX      src/main.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/parse/parser.h:8,
                 from src/main.cc:10:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
In file included from ./src/parse/parser.h:10:0,
                 from src/main.cc:10:
./src/parse/scanner.h:52:7: warning: base class ‘struct re2c::ScannerState’ has a non-virtual destructor [-Weffc++]
 class Scanner: private ScannerState
       ^
  CXX      src/parse/code.o
In file included from ./src/parse/code.h:9:0,
                 from src/parse/code.cc:1:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  CXX      src/parse/input.o
  CXX      src/parse/scanner.o
In file included from src/parse/scanner.cc:12:0:
./src/parse/scanner.h:52:7: warning: base class ‘struct re2c::ScannerState’ has a non-virtual destructor [-Weffc++]
 class Scanner: private ScannerState
       ^
  CXX      src/parse/unescape.o
  CXX      src/util/s_to_n32_unsafe.o
  CXX      src/util/range.o
In file included from ./src/util/range.h:10:0,
                 from src/util/range.cc:1:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
  GEN      src/parse/parser.cc
  GEN      src/parse/lex.cc
  CXX      src/parse/lex.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ../src/parse/lex.re:13:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
In file included from ../src/parse/lex.re:18:0:
./src/parse/scanner.h:52:7: warning: base class ‘struct re2c::ScannerState’ has a non-virtual destructor [-Weffc++]
 class Scanner: private ScannerState
       ^
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ../src/parse/lex.re:13:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
../src/parse/lex.re: In member function ‘uint32_t re2c::Scanner::lex_cls_chr()’:
../src/parse/lex.re:616:35: warning: conversion to ‘uint32_t {aka unsigned int}’ from ‘long int’ may alter its value [-Wconversion]
../src/parse/lex.re: In member function ‘uint32_t re2c::Scanner::lex_str_chr(char, bool&)’:
../src/parse/lex.re:648:36: warning: conversion to ‘uint32_t {aka unsigned int}’ from ‘long int’ may alter its value [-Wconversion]
  GEN      src/parse/lex_conf.cc
  CXX      src/parse/lex_conf.o
In file included from ../src/parse/lex_conf.re:8:0:
./src/parse/scanner.h:52:7: warning: base class ‘struct re2c::ScannerState’ has a non-virtual destructor [-Weffc++]
 class Scanner: private ScannerState
       ^
  CXX      src/parse/parser.o
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from ./src/parse/parser.ypp:20:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RegExp*>’:
./src/ir/regexp/regexp.h:54:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RegExp*, std::less<re2c::RegExp*>, std::allocator<re2c::RegExp*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::RangeSuffix*>’:
./src/ir/regexp/encoding/range_suffix.h:29:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::RangeSuffix*, std::less<re2c::RangeSuffix*>, std::allocator<re2c::RangeSuffix*> >’ has a non-virtual destructor [-Weffc++]
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<const re2c::Code*>’:
./src/parse/code.h:25:11:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<const re2c::Code*, std::less<const re2c::Code*>, std::allocator<const re2c::Code*> >’ has a non-virtual destructor [-Weffc++]
In file included from ./src/parse/parser.h:10:0,
                 from ./src/parse/parser.ypp:32:
./src/parse/scanner.h:52:7: warning: base class ‘struct re2c::ScannerState’ has a non-virtual destructor [-Weffc++]
 class Scanner: private ScannerState
       ^
In file included from ./src/ir/regexp/regexp.h:7:0,
                 from ./src/ir/dfa/dfa.h:9,
                 from ./src/parse/parser.ypp:20:
./src/util/free_list.h: In instantiation of ‘class re2c::free_list<re2c::Range*>’:
./src/util/range.h:37:12:   required from here
./src/util/free_list.h:10:7: warning: base class ‘class std::set<re2c::Range*, std::less<re2c::Range*>, std::allocator<re2c::Range*> >’ has a non-virtual destructor [-Weffc++]
 class free_list: protected std::set<_Ty>
       ^
src/parse/parser.cc: In function ‘int yyparse()’:
src/parse/parser.cc:1420:10: warning: conversion to ‘yytype_int16 {aka short int}’ from ‘int’ may alter its value [-Wconversion]
   *yyssp = yystate;
          ^
src/parse/parser.cc:1425:38: warning: conversion to ‘long unsigned int’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
       YYSIZE_T yysize = yyssp - yyss + 1;
                                      ^
  GEN      src/conf/parse_opts.cc
  CXX      src/conf/parse_opts.o
  CXXLD    re2c
cp ./bootstrap/doc/re2c.1 doc/re2c.1
Reconfigure to rebuild docs: ./configure --enable-docs
make[1]: Leaving directory`/opt/download/re2c-0.15.3'

**Comment by skvadrik** [comment]
Most of the warnings are ```-Weffc++```: gcc-4.8.3 complains that base class ```std::set``` has no virtual destructor (almost all warnings are about ```class free_list```). There's also a couple of ```-Weffc++``` warnings about ```class Scanner: private ScannerState```.

gcc-4.9.3 and higher reports no ```-Weffc++``` warnings (perhaps they fixed ```-Weffc++``` somehow). There's a lot of bug reports related to this, e.g. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16168 .

So there's no real danger, but I understand that the warning is annoying (especially because it hides a couple of sensible ```-Wconversion``` warnings). I think inheritance can be replaced with simple inclusion.

However the warnings cause no build or runtime failures, so the fix will probably have to wait until next major release.

**Comment by dnuffer** [comment]
I've rarely found -Weffc++ to be useful. There's too many situations where you want to actually violate the effective c++ guidelines. Most of them are things like avoid doing "x" except when "y" or "z". And in some past releases of gcc you'd get warnings just from including things from the standard library.

**Comment by skvadrik** [comment]
I find this part of ```-Weffc++``` helpful: "Define a copy constructor and an assignment operator for classes with dynamically-allocated memory". A couple of times forbidding copy constructor helped me fix the things that seemed totally unrelated.

**Comment by skvadrik** [comment]
Closing as this is obsolete now (the code has changed and `free_list` has been removed in https://github.com/skvadrik/re2c/commit/8bb8100853efac624bd62160643c1e2d1544bd0d). If this is still an issue, I suggest disabling `-Weffc++` in compiler flags when configuring re2c.
