### ISSUE TITLE
rst2man.py depreciated in RHEL7

### ISSUE THREAD

**Issue by CRCinAU** [skvadrik/re2c#133]
When trying to build re2c as a package, rst2man.py is not available.

rst2man is available via the python-docutils package - however even if this is present, building documentation via the --enable-docs fails during the configure stage.

As such, I believe the check in configure.ac should be more like:
```
AM_COND_IF([REBUILD_DOCS], [
    AC_CHECK_PROG(RST2MAN, rst2man.py, yes, no)
    AC_CHECK_PROG(RST2MAN, rst2man, yes, no)
    AS_IF([test "x$RST2MAN" = "xno"], [
        AC_MSG_ERROR([need rst2man.py or rst2man for --enable-docs])
    ])
])
```
Suggestions?

**Comment by skvadrik** [comment]
Thanks for reporting. I think it is better to use ```AC_CHECK_PROGS```:
```
- AC_CHECK_PROG(RST2MAN, rst2man.py, yes, no)
+ AC_CHECK_PROGS(RST2MAN, [rst2man rst2man.py], no)
```
See commit https://github.com/skvadrik/re2c/commit/c105527ab420f9cb392e39637373236f82e28d75.

**Comment by CRCinAU** [comment]
Thanks!

Just thought that I'd post that in packaging this for RHEL7, I used the following in the spec file to work around it at this stage:

%build
%configure
%{__make} re2c
rst2man doc/manpage.rst.in re2c.1

%install
%{__rm} -rf %{buildroot}
%{__install} -Dp -m0755 re2c %{buildroot}%{_bindir}/re2c
%{__install} -Dp -m0644 re2c.1 %{buildroot}%{_mandir}/man1/re2c.1

Your solution is obviously better than this - but I know nothing about the autotool functions - so just took a wild guess.... I can confirm that the above works on RHEL7 though :)

**Comment by CRCinAU** [comment]
Looking at the commit, it may be worthwhile to update this line too:
```
AC_MSG_ERROR([need rst2man.py for --enable-docs])
```

As now it doesn't require JUST rst2man.py - it can use rst2man as well :)

**Comment by skvadrik** [comment]
True. :)
https://github.com/skvadrik/re2c/commit/615773a3ee16b8ac7e6aa93dd4656bfc3efdd189
