### ISSUE TITLE
problem with push scanner

### ISSUE THREAD

**Issue by jcw** [skvadrik/re2c#134]
I'm running into a problem with creating a push scanner. It works brilliantly when feeding the scanner 3 chars at a time, it works in _some_ cases when feeding it in chunks of 2, and it fails when feeding it single characters at a time.

The source code has been stripped to its bare essentials, under 100 lines - see the attached [main.re](https://github.com/skvadrik/re2c/files/89429/main.txt). I'm using v0.15.3 on Mac OSX, the C code is generated with `re2c -s -c -f -o main.c main.re`

Output with 3 (on line 77) - lines folded together for brevity:

```
null  nul <null>  => 5
false  fal <false>  => 6
true  tru <true>  => 7
```

Output when fed 2 characters at a time:

```
null  nul <null>  => 5
false  => -1
true  tru <true>  => 7
```

Output with when fed single characters (other tests have led to segfaults):

```
null  => -1
false  => -1
true  => -1
```

The goal I'm after is to be able to feed the scanner individual characters, eventually - i.e. that last case.

I'm not very experienced with re2c - maybe I'm doing something wrong? Would welcome help, tips, etc.

Thanks,
-jcw

**Comment by skvadrik** [comment]
Perhaps you should have a look at re2c examples: http://re2c.org/examples/examples.html

This one in particular explains how to refill buffer: http://re2c.org/examples/example_03.html

The best way to fix your program is to take one of the examples as a basis. Meanwhile, I'll try to tune your code a bit.

**Comment by jcw** [comment]
Thanks for the quick reply - I did look, I have now found a solution, as follows:

```
static int feed1 (const void* ptr, int len) {
    if (limit + len > buffer + sizeof buffer)
        return -2;
    memcpy(limit, ptr, len);
    limit += len;
    if (limit - cursor < YYMAXFILL)   // ADDED
        return 0;                     // ADDED
    uint8_t yych;
    int yyaccept;
    /*!re2c
        ...
 ```

**Comment by jcw** [comment]
Thanks for pointing to that particular example, Ulya - I hadn't looked at this for this context (thinking that "arbitrarily large" did not apply to this case... doh).

**Comment by skvadrik** [comment]
If your lexical grammar is restricted over certain charset (say, none of the lexemes contains ```0x00``` byte), then you don't need ```YYFILL``` at all and you don't have to read more chars than necessary (see the very first exampe, the one about sentinel method: http://re2c.org/examples/example_01.html).

However, I strongly recommend you to avoid writing code like this:
```
    if (limit - cursor < YYMAXFILL)   // ADDED
        return 0;                     // ADDED
```
re2c generates all the necessary checks; if you have to insert them manually it means that you misuse re2c API.

I haven't fully analysed your code yet, bt I'll probably post some notes and suggestions when I do.

Also, this might be of interest for you, we have a couple of JSON lexers in our test suite: https://github.com/skvadrik/re2c/blob/master/re2c/test/php20150211_json_scanner.igc.re (taken from PHP sources) and https://github.com/skvadrik/re2c/blob/master/re2c/test/input_custom_mjson.--input%28custom%29.re (this one uses generic input API: http://re2c.org/manual/features/generic_api/generic_api.html to override re2c-generated checks for the end of buffer, but I think it's not a good solution).

**Comment by jcw** [comment]
Thx for the pointers. I did examine the PHP one in some detail, but it does too much for me, and makes some assumptions about its (bigger) environment. I now have a version which works while being fed with single characters - attached here as [main.re.txt](https://github.com/skvadrik/re2c/files/89578/main.re.txt) - it now does the entire JSON syntax, I think - and includes some simple test cases, all in 114 LOC. Should build and run out of the box - would gladly welcome any improvements you can think of to make it more purely adhere to re2c idioms. Whenever you have time and are looking for a distraction, that is ...

Thanks for your tips, I'll keep tweaking this as I learn more about re2c. Great tool!

**Comment by skvadrik** [comment]
By the way, valgrind (http://valgrind.org/) suggests that ```memcpy``` on line 77 should be ```memmove``` (memory areas may overlap):
```
diff --git a/main.re b/main.re
index a32b5a0..0ccf080 100644
--- a/main.re
+++ b/main.re
@@ -74,7 +74,7 @@ static int feed (uint8_t ch) {
     */
 fill:
     if (start > buffer) {
-        memcpy(buffer, start, limit-start);
+        memmove(buffer, start, limit-start);
         int off = start-buffer;
         start -= off;
         marker -= off;
```

Valgrind's tool Memcheck is very good at finding errors like this. I run Memcheck with the following options:
```
#!/bin/sh

supp="$HOME/misc/valgrind/all.supp"

G_SLICE=always-malloc \
G_DEBUG=gc-friendly   \
\
GLIBCXX_FORCE_NEW=1 \
valgrind \
    --track-origins=yes          \
    --trace-children=yes         \
    --num-callers=50             \
    --track-fds=yes              \
    --leak-check=full            \
    --show-reachable=yes         \
    --malloc-fill=0xa1           \
    --free-fill=0xa1             \
    --suppressions=$supp         \
"$@"
```

**Comment by jcw** [comment]
It's a good point to make, but the copy is always downwards, so _if_ (!) memcpy guarantees that it always copies from low to high, then either one should work. There are more bugs in there, I noticed ("n" handling  in feeds() being one).

**Comment by skvadrik** [comment]
Feeding one input character at a time is highly inefficient. If the target environment is memory-constrained, you should allocate a small buffer and feed lexer in chunks of buffer size (minus the length of the input that remains in buffer when ```YYLIMIT - YYCURSOR < n``` check fails and lexer calls ```YYFILL```).

The idea is, when lexer calls ```YYFILL``` it asks you to provide at least ```n``` characters, but the more characters you provide the better (```YYFILL``` should occur as rarely as possible for maximum efficiency). I see no reason why you might want to fill in a single character while you can as well fill the whole buffer.

**Comment by jcw** [comment]
Yes, I am well aware of that - my context is an embedded µC where RAM can be very scarce, JSON is coming in via serial, and the µC tends to be doing nothing in between. When this data comes in "[1,2]\n", I would like to parse things char-by-char and ideally immediately end processing the moment either "]" or "\n" has been seen - with a next round of JSON possibly coming in soon thereafter. There is no room to copy thing, even the token buffer is something I would prefer to avoid, but can't. Oh, and no malloc... so memory areas tend get allocated statically and remain single-purpose forever.

**Comment by jcw** [comment]
This scanner - [main-tiny.re.txt](https://github.com/skvadrik/re2c/files/89757/main-tiny.re.txt) - needs just 36 bytes of RAM state (plus some stack space). It properly scans `"..."`, `[...]`, and `{...}`, but does not grab the complete tokens in other cases (unless inside [] or {}). So instead of "null", the scanner only takes "n" and then stops.

Output from this latest revision is as follows, showing the token results for a number of test strings:

```
$ re2c -s -c -f --input custom -o main.c main.re
$ cc -std=gnu99    main.c   -o main
$ ./main
[]
 vec<[> vec<]> => 1
{}
 map<{> map<}> => 2
"abc"
 str<"> chr<a> chr<b> chr<c> str<"> => 3
123456789
 num<1> => 4
null
 key<n> => 5
false
 key<f> => 5
true
 key<t> => 5
[null]
 vec<[> key<null> vec<]> => 1
[false]
 vec<[> key<false> vec<]> => 1
[true]
 vec<[> key<true> vec<]> => 1
[123,{"abc":-12.34},"\"",12.34e-56,[1,2],3]
 vec<[> num<123> map<{> str<"> chr<a> chr<b> chr<c> str<"> num<-12.34> map<}> st
r<"> esc<\"> str<"> num<12.34e-56> vec<[> num<1> num<2> vec<]> num<3> vec<]> =>
1
2.2250738585072014e-308
 num<2> => 4
-2.2250738585072014e-308
 => -1
[-2.2250738585072014e-308]
 vec<[> num<-2.2250738585072014e-308> vec<]> => 1
```

This is ok with me for now, though I'm intrigued as to why the scanner is not working in a greedy fashion. Probably just my lack of understanding of the underlying theory.

Anyway, it's been a fascinating exploration!

**Comment by skvadrik** [comment]
I would probably recommend the following:
* use generic API
* make ```YYPEEK()``` a blocking call that hangs untill it receives the next character. Here is a couple of examples http://skvadrik.github.io/aleph_null/posts/re2c/2015-01-15-input_model_custom.html how to override ```YYPEEK```, but you can make it a loop or anything.
* disable ```YYFILL``` with ```re2c:yyfill:enable = 0;```. It's no longer needed since all the checking-refilling logic is moved to ```YYPEEK```, it can never dereference an invalid pointer or do anything harmful.

I'll get back to it in the evening and try to make a working example of what I mean.

> Anyway, it's been a fascinating exploration!

I've always been amused at the multitude of ways one can use re2c ;)

**Comment by jcw** [comment]
Hm, tricky. If YYPEEK blocks, this is no longer a push model. Could this be turned around? I.e. whenever it wants to block, return instead, and then come back in when a new character is ready? The problem is that it may be hard to get back to the YYPEEK call site, which is probably deep inside the generated code.

The read-ahead is also going to be an issue. I really don't want to feed more than at most one character past the closing ']', '}", etc - the use case being JSON coming in over serial with a trailing "\n" appended. There is no guarantee that anything more will come in (for example if JSON is used as request/reply mechanism).

These edge cases are most educational. I'd love to find out if re2c can handle it, otherwise a hand-crafted scanner might be the simpler way out. The grammar is simple enough, after all.

**Comment by jcw** [comment]
I've posted the code as a [gist](https://gist.github.com/jcw/1a5b68d51f4c96557db1), FWIW.

**Comment by skvadrik** [comment]
Here is my variant (I tried to make as few changes to the original program as possible):
[main.re.txt](https://github.com/skvadrik/re2c/files/91112/main.re.txt)

Generate, compile and run as follows:
```
re2c -c --input custom -o main.c main.re
cc -std=gnu99 main.c -o main
./main
```
The program will wait for input (just as it would wait for bytes coming over serial). You can type in JSON, in chunks on any size you like, and lexer will react.

The program is very rough --- it's just a demonstration. If it turns out to be of interest to you, I have a couple of fixes in mind.

**Comment by jcw** [comment]
Thanks, it looks good. The inversion of control is a stumbling block for me, though. I really need a push parser, not one that turns around and starts busy-waiting for input. I went ahead and rolled my own for this case, but I'll definitely revisit re2c for other tasks.

Feel free to close this issue, as it probably no longer useful to keep it open / pending.
