### ISSUE TITLE
In installation "make check" give syntax error

### ISSUE THREAD

**Issue by Samuel006** [skvadrik/re2c#135]
My OS:
ASP Linux Server 5 (Red Hat Enterprise Linux 5.1). 
gcc-3.4.6.-9,  bash-3.0-19.6
I try to install re2c-0.16.tar.gz:

#> ./configure - OK
#> make - OK
#> make check - test failed
#> make tests - test failed:
make  all-am
make[1]: Entering directory `/root/new_packs/re2c-0.16'
Reconfigure to rebuild docs: ./configure --enable-docs
make[1]: Leaving directory `/root/new_packs/re2c-0.16'
./run_tests.sh
./run_tests.sh: line 52: syntax error near unexpected token `"$arg"'
./run_tests.sh: line 52: `              * ) tests+=("$arg") ;;'
make: *** [tests] Ошибка 2

I replaced string 52 in file ./run_tests.sh: 
`              * ) tests+=("$arg") ;;' 
to line:
`              * ) tests=${tests}${arg} ;;'
And now "make check" work excelent. 
Please check my correction.

**Comment by skvadrik** [comment]
Your fix you is a bit incorrect: it glues all arguments together in one giant string (which is further interpreted as a single filename). The error is exposed when one invokes script with multiple filenames (something that `make check` does not).

I suggest the following fix: https://github.com/skvadrik/re2c/commit/d4c322c8fa2c40fc82d05fc610b087f8102b5617

**Comment by Samuel006** [comment]
I see. Thanks. All works properly with your fix, but syntax error appear one more time.
Need to replace string 217. From:
wait_pids+=("$!")
To:
wait_pids[${#wait_pids[@]}]=$!
Is it right?

**Comment by skvadrik** [comment]
Yes, that's correct. I should have checked all occurrences. :). Fix: https://github.com/skvadrik/re2c/commit/0bf6f26a6d553963ee60229c75772b8f6ca84781

**Comment by Samuel006** [comment]
Thank you.  : )
