### ISSUE TITLE
run_tests.sh fail when running configure script with absolute path

### ISSUE THREAD

**Issue by jaydee-io** [skvadrik/re2c#137]
When running the `configure` script with an absolute path, `run_tests.sh` fail.
See [output.txt](https://github.com/skvadrik/re2c/files/144618/output.txt) and [test-suite.log](https://github.com/skvadrik/re2c/files/144619/test-suite.txt) for details.
```bash
$ tar -xf /tmp/packages/re2c-0.16.tar.gz -C /tmp/sources/re2c-0.16 --strip-components 1
$ cd /tmp/build/re2c-0.16
$ /tmp/sources/re2c-0.16/configure --prefix=/tmp/install --enable-docs
$ make -j8 bootstrap docs
$ make -j8 check
```
The same using a relative path leads to `run_tests.sh` success.
```bash
$ tar -xf /tmp/packages/re2c-0.16.tar.gz -C /tmp/sources/re2c-0.16 --strip-components 1
$ cd /tmp/build/re2c-0.16
$ ../../sources/re2c-0.16/configure --prefix=/tmp/install --enable-docs
$ make -j8 bootstrap docs
$ make -j8 check
```

**Comment by skvadrik** [comment]
Confirmed, thanks for reporting.
Yet I'm not sure what is the simplest portable way to tell if a path is absolute/relative.

**Comment by jaydee-io** [comment]
I'm currently working to submit you a patch of `run_tests.sh` using `readlink -f` to convert to absolute path.

But first, I'm not sure if it's portable to Wine.
And under Mac OS X the default `readline` command doesn't support `-f`option. We need to use `greadlink` instead.
```bash
brew install coreutils
greadlink -f file.txt
```

**Comment by skvadrik** [comment]
Sadly, `readlink` is also non-POSIX.

I think I've come up with a more portable fix: simply copy all test sources to `test_blddir` and keep using relative paths.

**Comment by jaydee-io** [comment]
Yes, you're right.
Your fix is surely simpler and not concerned by portability issue.

**Comment by skvadrik** [comment]
Not-so-quick and dirty fix: https://github.com/skvadrik/re2c/commit/7875e6c8e106735ddc8928921d88fef64e1d61aa

**Comment by jaydee-io** [comment]
Commit 7875e6c fix the problem.
Thanks !
