### ISSUE TITLE
website improvement

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#138]
As suggested by asmwarrior in re2c-devel@lists.sourceforge.net mailing list:

1. homepage: mention sourceforge repo
2. homepage: mention mail archieves
3. homepage: list major re2c users (php, yasm, ninja, etc.)
4. install page: link to old releases
5. manual pages: add navigation tree on left

**Comment by skvadrik** [comment]
http://re2c.org has been updated.

**Comment by asmwarrior** [comment]
Great job, I think my suggestions in the maillist are all implemented. Thanks for your contribution. Asmwarrior.

**Comment by skvadrik** [comment]
Cool. :)
