### ISSUE TITLE
Rule precedence in case of lua style comments

### ISSUE THREAD

**Issue by philippschaefer** [skvadrik/re2c#139]
I go with the following grammar:

```
/*!re2c
  '--[' '='* '[' { return findCommentSpanEnd(); }
  '--'[^\000\n]* { return LEX_LINE_COMMENT; }
  
  '\000' { return LEX_EOF; }
  '\n'   { return LEX_EOL; }
  *      { return LEX_INVALID; }
*/
```

(Following the manual) I expect the rule in the first line to have precedence over the rule in the second line if there is an ambigious situation. However, the generated lexing code is the following (v0.16):
```
`/* Generated by re2c 0.16 on Thu Apr 21 14:36:55 2016 */
#line 1 "grammar.y"

#line 5 "grammar.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\n':	goto yy6;
	case '-':	goto yy8;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 5 "grammar.y"
	{ return LEX_EOF; }
#line 20 "grammar.c"
yy4:
	++YYCURSOR;
yy5:
#line 7 "grammar.y"
	{ return LEX_INVALID; }
#line 26 "grammar.c"
yy6:
	++YYCURSOR;
#line 6 "grammar.y"
	{ return LEX_EOL; }
#line 31 "grammar.c"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy9;
	default:	goto yy5;
	}
yy9:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '[':	goto yy13;
	default:	goto yy12;
	}
yy10:
#line 3 "grammar.y"
	{ return LEX_LINE_COMMENT; }
#line 47 "grammar.c"
yy11:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy12:
	switch (yych) {
	case 0x00:
	case '\n':	goto yy10;
	default:	goto yy11;
	}
yy13:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case '\n':	goto yy10;
	case '=':	goto yy13;
	case '[':	goto yy15;
	default:	goto yy11;
	}
yy15:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 0x00:
	case '\n':	goto yy16;
	default:	goto yy11;
	}
yy16:
#line 2 "grammar.y"
	{ return findCommentSpanEnd(); }
#line 79 "grammar.c"
}
#line 8 "grammar.y"
```
yy15 excludes the first rule except for the excluded characters from the second rule. Basically it should not exist at all and directly skip to yy16.

Any suggestions?

With best regards
Philipp Schäfer

**Comment by skvadrik** [comment]
Hello Philipp!

Actually, it's not a bug. re2c has two rules to resolve ambiguous cases:
1. prefer longest match
2. prefer rule with smaller number

In this case second rule shadows all the cases of the first rule except those that end with  ```[\000\n]```. For example, string ```--[===[``` matches the first rule, but a longer string ```--[===[a``` matches the second rule, so re2c prefers the second rule (lexer goes to ```yy11```, increments ```YYCURSOR``` and loops until it finds ```[\000\n]```).

I  understand that it is confusing, but that's how things work with greedy deterministic parsing.

Perhaps you can change the rules a bit? Otherwise,  you can manually override rule precedence by breaking lexer into two blocks:
```
/*!re2c
  '--[' '='* '[' { return findCommentSpanEnd(); }
  '--'           { goto comment; }

  '\000' { return LEX_EOF; }
  '\n'   { return LEX_EOL; }
  *      { return LEX_INVALID; }
*/

comment:
/*!re2c
  [^\000\n]* [\000\n] { return LEX_LINE_COMMENT; }
*/
```
Hope that helps, and thanks for reporting. At first I also thought i's a bug. ;)

**Comment by philippschaefer** [comment]
Thanks for the quick reply!

I will adjust my full lexer code according to your suggestions. I am sorry for reporting an issue where there is expected behavior...

Maybe it would be a good idea to adjust the wording in the manual to include the second precedence rule for longest match. Currently it states:

> Rules consist of a regular expressions along with a block of C/C++ code that is to be executed when the associated regular expression is matched. You can either start the code with an opening curly brace or the sequence :=. When the code with a curly brace then re2c counts the brace depth and stops looking for code automatically. Otherwise curly braces are not allowed and re2c stops looking for code at the first line that does not begin with whitespace. If two or more rules overlap, the first rule is preferred.

Thanks for the great lexer as it is!

**Comment by skvadrik** [comment]
Sure, the manual needs to be fixed. I can't do it right now, but I've opened an issue: https://github.com/skvadrik/re2c/issues/140
Feel free to submit any other suggestions.
