### ISSUE TITLE
Update manual

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#140]
Manual on the website http://re2c.org is should be fixed and updated. This issue is a reminder to do it, as well as a place to pile all relevant notes and ideas. TODO:
- explain rule precedence (longest match, earliest rule)

**Comment by skvadrik** [comment]
Describe control flow in case of multiple re2c blocks as requested in https://github.com/skvadrik/re2c/issues/143.

**Comment by skvadrik** [comment]
Add benchmarks (see #149)

**Comment by skvadrik** [comment]
Explain control flow in conditions (see bug #151).

**Comment by skvadrik** [comment]
Add section (tutorial, guidelines, etc.) about lexer termination and buffer refilling. In particular, highlight the following topics:

- `YYFILL()` vs sentinel termination metod
- what must be updated by `YYFILL`
- how to arrange pointers for `YYFILL`: struct vs standalone pointers (include examples of generated assembly for both cases)
- how tag implementation depends on the presence of `YYFILL`: absolute vs relative tags

**Comment by skvadrik** [comment]
Add lower version reminders to avoid confusion like this: http://stackoverflow.com/questions/39738102/syntax-error-from-default-rule/39766309#39766309

**Comment by skvadrik** [comment]
Add skeleton documentation: : http://skvadrik.github.io/aleph_null/posts/re2c/2015-01-15-input_model_custom.html and http://skvadrik.github.io/aleph_null/posts/re2c/2015-01-13-input_model.html

**Comment by skvadrik** [comment]
Complete Wikipedia article: https://github.com/skvadrik/re2c/issues/168

**Comment by skvadrik** [comment]
Document comment syntax: https://github.com/skvadrik/re2c/issues/180

**Comment by skvadrik** [comment]
Document operator precedence: #183

**Comment by pmetzger** [comment]
Moving my documentation issue here per @skvadrik (and although this is different in `master` I think the version there is mangled):

In the man page:

>       re2c:yyfill:enable = 1;
>              Set this to zero to suppress  generation  of  YYFILL  (n).  When
>              using this be sure to verify that the generated scanner does not
>              read behind input. Allowing this behavior might introduce  sever
>              security issues to you programs.

You probably want this to read:

>              Set this to zero to suppress  generation  of  YYFILL  (n).  When
>              using this**,** be sure to verify that the generated scanner does not
>              read **beyond** the **available** input. Allowing this behavior
>              might introduce **severe** security issues to **your** programs.

**Comment by skvadrik** [comment]
Fix clone URLs on install page.

**Comment by skvadrik** [comment]
Amend the list of contributors here: http://re2c.org/about/about.html

**Comment by skvadrik** [comment]
Update quoting in examples: https://github.com/skvadrik/re2c/issues/199

**Comment by skvadrik** [comment]
Add examples for `--posix-captures` and `--input custom --tags` mentioned here: https://github.com/skvadrik/re2c/issues/209#issuecomment-400604386

**Comment by Des-Nerger** [comment]
> With both `-P --posix-captures` and `T --tags` options re2c uses efficient submatch extraction algorithm described in the Tagged Deterministic Finite Automata with Lookahead paper.
Why isn't that efficient algorithm applied when only `--posix-captures` is specified? Are there reasons to not always use it?
If I only want to use posix-captures, should I also add `--tags`, just for the sake of performance?

**Comment by Des-Nerger** [comment]
Maybe it's just me, but this sentence:
> With both `-P --posix-captures` and `T --tags` options re2c uses efficient submatch extraction algorithm described in the Tagged Deterministic Finite Automata with Lookahead paper.

sounds ambiguous to me. At first I thought that the both options should be specified simultaneously in order for the algorithm to be applied.

**Comment by sergeyklay** [comment]
My 2 cents. It will be awesome to have improved "[Options & arguments](https://re2c.org/examples/example_14.html)" page. Consider a real world example:

```

$ pip --help

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to WARNING, ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host as trusted, even though it does not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for download. Implied with --no-index.
  --no-color                  Suppress colored output
```

These is positional "commands" as well as options.

**Comment by sergeyklay** [comment]
BTW, milestione 0.17 is outdated.

**Comment by skvadrik** [comment]
@Des-Nerger Thanks for spotting this, now I see that it sounds ambiguous.

@sergeyklay Yes, it's hard to find the right option without `grep` or `Ctrl+F`. Re2c does not have commands, so options cannot be naturally grouped by the command. But perhaps they can be grouped in some other way (e.g. code generation options, internal options, etc. --- the way they are grouped in src/options/opt.h:78). I'm not sure it will be useful. Do you have a particular layout in mind? 

Removing milestone. Long time ago, right after migration on github I thought they might be useful, but the time has shown that for a research project like re2c without clear planning milestones do not make much sense.

**Comment by sergeyklay** [comment]
@skvadrik In general I'm interested whether such task can be easily implemented using re2c only or not. Another way is to implement options parser using re2c with lemon.

**Comment by skvadrik** [comment]
@sergeyklay Apologies, I totally mis-read your question --- I thought you meant that re2c help message should be improved. As for parsing command-line options for pip --- I think this can be done with re2c only (and a bit of glue code). A good example is [re2c own option parser](https://github.com/skvadrik/re2c/blob/master/src/options/parse_opts.re). Whenever it encounters an option that requires special handling, it goes to a small dedicated lexer block. Also the parser  handles `argv` from `main` as distinct strings, without buffering them in a single string. If some common lexer rules must be shared between such blocks, it can be done with `-r` option.

Extending the example is a good idea, I will do it if I have time.

**Comment by skvadrik** [comment]
@sergeyklay Here is an example that uses conditions (build instructions in comments in the file): 
[cmdargs.re.txt](https://github.com/skvadrik/re2c/files/3715044/cmdargs.re.txt). It has roughly the structure of pip arguments: two commands, each has a few private options, and also a few common options. Tags are not useful in this kind of task because all options are a priori split into separate strings.

**Comment by sergeyklay** [comment]
@skvadrik Thank you very much for your help and providing an example.

**Comment by skvadrik** [comment]
@sergeyklay You are welcome! In future, it would be better if re2c allows to mix conditional and non-conditional blocks (in my example 'abi' and 'path' conditions should be ordinary blocks not involved in the initial conditional switch generated by re2c), but for now re2c does not allow mixed blocks with `-c`.

**Comment by skvadrik** [comment]
@Des-Nerger I re-worded the manual to avoid ambiguity: http://re2c.org/manual/manual.html#submatch-extraction.

**Comment by sergeyklay** [comment]
@skvadrik Could you please suggest better approach to handle `=`  between an option and its value.
Consider the following example:
```
/*!re2c
    re2c:define:YYCTYPE = 'unsigned char';
    re2c:yyfill:enable = 0;
    re2c:yych:conversion = 1;

    end = "\x00";

    <init> * { ERROR("bad command: %s\n", *argv); }
    <init> "freeze"  end => freeze  { cmd.kind = FREEZE;  goto loop; }
    <init> "install" end => install { cmd.kind = INSTALL; goto loop; }

    <*> * { ERROR("bad option: %s\n", *argv); }

    <freeze, install> "--quiet" end { cmd.quiet = true; goto loop; }

    <freeze> "--requirement" end { NEXT(); ppath = &cmd.freeze.requirement; goto yyc_path; }
    <freeze> "--local"       end { cmd.freeze.local = true; goto loop; }

    <install> "--root" end { NEXT(); ppath = &cmd.install.root; goto yyc_path; }
    <install> "--abi"  end { NEXT(); goto yyc_abi; }

    <path> *          { ERROR("bad path: %s\n", *argv); }
    <path> [a-z]+ end { *ppath = *argv; goto loop; }

    <abi> *             { ERROR("bad ABI: %s\n", *argv); }
    <abi> "pypy_41" end { cmd.install.abi = 41; goto loop; }
    <abi> "pypy_42" end { cmd.install.abi = 42; goto loop; }
*/
```

I would like to have a short option, say `-r` and it's long equivalent `--requirement` so that provide an ability to use  the following forms
```
-r path
-r=path
--requirement path
--requirement=path
```

I tried to change a bit the rule:
```diff
- <freeze> "--requirement" end { NEXT(); ppath = &cmd.freeze.requirement; goto yyc_path; }
+ <freeze> ("-r" | "--requirement" "="?) end { NEXT(); ppath = &cmd.freeze.requirement; goto yyc_path; }
```

and it works for the following forms:
```
-r path
--requirement path
```

but doesn't works for the following forms:
```
-r=path
--requirement=path
```

```
bad option: --requirement=foo
```

**Comment by skvadrik** [comment]
You are on the right track, but you forgot that in case of `--requirement=something` this is all one string, and thus one argument in `argv`, so `NEXT` should not be called. Here is a modified example that works as you would expect: [cmdargs.re.txt](https://github.com/skvadrik/re2c/files/3723151/cmdargs.re.txt). The changed part looks like this:
```
    <freeze> ("--requirement" | "-r") ("\x00" | "=") {
        if (YYCURSOR[-1] == 0) NEXT();
        cmd.freeze.requirement = YYCURSOR;
        goto yyc_path;
    }
```
We expect _either_ `\0`, or `=` after the option. In case of `\0` we skip to the next argument by calling `NEXT`; in case of `=` there is no need to change cursor position. Then we set the path to `YYCURSOR` (it points either to the beginning of next `argv` argument in case of `\0`, or to the middle of the current `argv` argument in case of `=`). Then we proceed to lexing the path.

**Comment by sergeyklay** [comment]
Thank you very much!

**Comment by sergeyklay** [comment]
@skvadrik I'm sorry for bothering you again, but I have (I sincerely hope) the last question regarding to parsing options. I've adopted your examples to my application and all seems is ok. However, doubts about one of my scenarios do not leave me:

```
cmdN [options] [--] <name>
```

Here `cmdN` is some command name, (say `greeting`). `options` are regular options as above. And `name` is required value. Optional `--` means remaining args are non-options and we need get a word and stop parsing. Some correct examples:

```sh
./app greeting John
./app greeting -- John
./app greeting --transform-name=uppercase John
./app greeting --transform-name=uppercase -- John
# Order doesn't matter
./app greeting John --transform-name=uppercase
```

These forms are not allowed (invalid):
```
./app greeting --
./app greeting
./app greeting --transform-name=uppercase
./app greeting --transform-name=uppercase --
./app greeting -- --transform-name=uppercase
```

It seems I have created the necessary scanner portion, but I still doubt about the solution (relevant part):
```c
   // application expects exactly one word for NAME
   // but for simplicity's sake, I will not point it out here
   name = [^\x00-][^\x00]*;

   <greeting> "--" end {
      // all remaining argv part is non-option
      // so it must be user name
      if (!(YYCURSOR = *++argv)) {
        // I use exceptions instead of boolean FALSE
        throw OptionException("Not enough arguments (missing: \"name\").");
      }

      cmd.greeting.name = YYCURSOR;
      goto yyc_name;
   }

   <greeting> name end {
      cmd.greeting.name = *argv;
      goto loop;
   }
```

I just would like you to take a look and maybe advise a better solution if I make a mistake.

**Comment by skvadrik** [comment]
> I'm sorry for bothering you again, but I have (I sincerely hope) the last question regarding to parsing options.

It's absolutely fine, you are welcome to ask. With re2c each use case is a different (and usually interesting) problem, and discussion helps both users and developers.

Regarding your solution, see the extended example [cmdargs.re.txt](https://github.com/skvadrik/re2c/files/3806500/cmdargs.re.txt), with a few remarks:

- If you keep going through the main loop after you saw the non-option separator `--` to process the remaining non-option arguments, you need to transition to a special condition (`name` in the example), or else the lexer might erroneously accept options after the separator.

- You need to deal with multiple non-option arguments, for example `./app greeting John Bob`or `./app greeting -- John Bob` or `./app greeting John -- Bob Alice` (multiple names may be ill-formed, but they still need to be handled). In the example I treat them as an error, but you may need different behaviour: e.g. accumulate all names in a vector, or take the last one.

- If the non-option separator `--` may occur with any command (not only `greeting`), then it should be handled by the same code for all commands, so instead of `<greeting> "--" end` you should have `<greeting, c1, ..., cN> "--" end` (in the example `<freeze, install> "--" end => name`).

- The case when name is not passed at all should be handled after the parse (I don't handle it in the example).

**Comment by sergeyklay** [comment]
Hm... interesting. Why the case when name is not passed at all should be handled after the parse? Could you elaborate on that a bit more. Anyway thank you again! :)

**Comment by skvadrik** [comment]
> Why the case when name is not passed at all should be handled after the parse? 

Can you suggest any other place to handle it? The name may be the last element of `argv`. It is not known until the end of parsing if the name has been parsed or not. Separator `--` is optional, so the check cannot be placed in the code for the `<name>` condition.

**Comment by sergeyklay** [comment]
To be able to perform tests I decided to create a test fixture. And I got an interesting bug. 
Let me provide steps to reproduce. I modified the last example as follows:

```bash
$ diff -u cmdargs.re.txt cmdargs.re.txt
```

```diff
--- cmdargs.re.txt	2019-11-05 11:46:20.000000000 +0200
+++ cmdargs.re.txt	2019-11-05 14:36:20.000000000 +0200
@@ -1,6 +1,37 @@
 #include <stdio.h>
 #include <string.h>

+#include <initializer_list>
+#include <memory>
+#include <vector>
+
+class Argv {
+ public:
+  Argv(std::initializer_list<const char*> args)
+    : m_argv(new char *[args.size()]), m_argc(args.size()) {
+    int i = 0;
+    auto iter = args.begin();
+    while (iter != args.end()) {
+        auto len = std::strlen(*iter) + 1;
+        auto ptr = std::unique_ptr<char[]>(new char[len]);
+
+        std::strncpy(ptr.get(), *iter, len);
+        m_args.push_back(std::move(ptr));
+        m_argv.get()[i] = m_args.back().get();
+
+        ++iter;
+        ++i;
+    }
+  }
+  char** argv() const { return m_argv.get(); }
+  size_t argc() const { return m_argc; }
+
+ private:
+  std::vector<std::unique_ptr<char[]>> m_args;
+  std::unique_ptr<char*[]> m_argv;
+  size_t m_argc;
+};
+
 // Build:
 //   $ re2c -W cmdargs.re -ci -ocmdargs.cpp
 //   $ c++ cmdargs.cpp -O2 -Wall -g -ocmdargs
@@ -123,7 +154,9 @@
     Cmd cmd;
     memset(&cmd, 0, sizeof(Cmd));

-    if (!parseopt(argv, cmd)) {
+    Argv args({"foo", "install", "--root", "xxx"});
+
+    if (!parseopt(args.argv(), cmd)) {
         printf("error\n");
         return 1;
     }
```

Then, compile with `-std=c++11` falg:
```bash
$ re2c -W cmdargs.re -ci -ocmdargs.cpp
$ c++ -std=c++11 cmdargs.cpp -O2 -Wall -g -ocmdargs
```

And calling `cmdargs` from a terminal **randomly** leads to segmentation fault. I tested various versions of gcc and clang on macOS and Debian:
```
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
INSTALL
	root: xxx
	abi: 0
	quiet: 0
	name: (null)
$ ./cmdargs
[1]    98388 segmentation fault  ./cmdargs
```

Here is lldb output:
```
$ lldb cmdargs
(lldb) target create "cmdargs"
Current executable set to 'cmdargs' (x86_64).
(lldb) run
Process 98853 launched: '..../cmdargs' (x86_64)
Process 98853 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x6f6f66)
    frame #0: 0x0000000100001911 cmdargs`parseopt(argv=0x0000000100300080, cmd=0x00007ffeefbff220) at cmdargs.cpp:456:24
   453 		}
   454 	/* *********************************** */
   455 	yyc_install:
-> 456 		yych = (unsigned char)*YYCURSOR;
   457 		switch (yych) {
   458 		case '-':	goto yy75;
   459 		case 'A':	goto yy76;
Target 0: (cmdargs) stopped.
```

**Comment by skvadrik** [comment]
Valgrind points at the error:
```
$ valgrind ./cmdargs 
==31687== Memcheck, a memory error detector
==31687== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==31687== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==31687== Command: ./cmdargs
==31687== 
==31687== Invalid read of size 8
==31687==    at 0x1099C0: parseopt(char**, Cmd&) (cmdargs.re:92)
==31687==    by 0x1092A6: main (cmdargs.re:159)
==31687==  Address 0x4e3bca0 is 0 bytes after a block of size 32 alloc'd
==31687==    at 0x483650F: operator new[](unsigned long) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==31687==    by 0x1091E1: Argv (cmdargs.re:11)
==31687==    by 0x1091E1: main (cmdargs.re:157)
[...]
```
Line 92 is the dereference of the next argument `if (!(YYCURSOR = *++argv)) return true;`, and the allocation of arguments happened at line 11 (in the constructor). The reason for the invalid read is that the code at line 92 expects C-style `argv` array  which is NULL- terminated (the last element of `argv` is `NULL`). When you converted to initializer list, you dropped this terminating `NULL` element. The code can be fixed by adding a fake `NULL` element at the end of initializer list, but a much cleaner solution IMO is to simply pass an `std::vector` to `parseopt` instead of trying to emulate NULL-terminated `argv`. See the updated example: [cmdargs.re.txt](https://github.com/skvadrik/re2c/files/3811632/cmdargs.re.txt).

**Comment by skvadrik** [comment]
> And calling `cmdargs` from a terminal randomly leads to segmentation fault.

Such "randomness" often is the case with memory access errors: the accessed address may happen to be mapped in the process address space with the right permissions, and it may even contain data that by accident happens to be what the programmer expected (zeroes in this case). Then the violation goes unnoticed. On a subsequent run memory layout is different and it fails.

Valgrind tracks all memory accesses and finds such errors: even if the program does not segfault, valgrind will report the violation. It is also very good at tracking uninitialized memory. I use a script similar to [this one](https://github.com/trofi/home/blob/master/bin/vg).

**Comment by sergeyklay** [comment]
Aha! Btw, I solved this problem in a dirty way:
```diff
Argv argv({
    "foo",
    "installl",
-   "--root"
+   "--root",
+   ""
});
```

and scanner:
```diff
loop:
-  if (!(YYCURSOR = *++argv)) return true;
+  YYCURSOR = *++argv;
+  if (!YYCURSOR || *YYCURSOR == '\0') return pr;
```

But your approach is more accurate. Thank you!

**Comment by skvadrik** [comment]
Let's close this and open individual issues for new bugs. Updating the manual is a never-ending process. :)
