### ISSUE TITLE
segvault with null terminated input

### ISSUE THREAD

**Issue by jcfp** [skvadrik/re2c#142]
hi,

a bug was reported in debian about a segvault in re2c with null terminated input:

> When re2c reads a file that is containing '&' (ampersand) that is followed by null byte, re2c is crashed due to heap overread.
> 
> The following is the reproducible steps:
> $ echo -ne "&\x00" > A
> $ re2c A
> Segmentation fault

I'm not sure if the ampersand is actually required, as it seems to segvault with other characters too as long as that null is at the end. The bug was reported against 0.13.5 but this reproduces with 0.16 too.

See the [debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823999) for more details.

**Comment by skvadrik** [comment]
Confirmed, thank you.

**Comment by skvadrik** [comment]
Here is a fix: https://github.com/skvadrik/re2c/commit/54711f61242c4ff4a744ab33d4cb5a3530ddcf02 :)

Just a case of forgotten `goto` which remained unnoticed for years.

**Comment by jcfp** [comment]
:thumbsup: Sure enough that does the job. Thanks!
