### ISSUE TITLE
Generated code is incorrent

### ISSUE THREAD

**Issue by sirzooro** [skvadrik/re2c#144]
I am translating grammars from RFC documents into re2c format and found case when generated code is incorrect:

```c
#include <stdio.h>

int test(const char* str)
{
    const char* tokStart = str;
    const char* YYMARKER; 
    /*!re2c
        re2c:define:YYCTYPE = "unsigned char";
        re2c:define:YYCURSOR = str;
        re2c:yyfill:enable = 0;
        
        CR = "\r"; // carriage return
        LF = "\n"; // %x0A ; linefeed
        CRLF = CR LF; // Internet standard newline
        HTAB = [\x09]; // %x09 ; horizontal tab
        SP = [\x20]; // %x20
        WSP = (SP | HTAB); // SP / HTAB ; white space
        LWS = (WSP* CRLF) WSP+; //  [*WSP CRLF] 1*WSP ; linear whitespace
        SWS = LWS?; // [LWS] ; sep whitespace
        HCOLON = (SP | HTAB)* ":" SWS; // *( SP / HTAB ) ":" SWS
        
        * { return 0; }
        "Test" HCOLON "test" { return 1; }
    */
}

int main()
{
    printf("%d\n", test("Test: test\r\n"));
    printf("%d\n", test("Test:test\r\n"));
    return 0;
}
```

Above code defines rules for parsing headers - in this case header "Test" with value "test", and as a result program should print "1" two times. However this is not the case for 1st string. for some reason generated code does not accept spaces after colon. Here is buggy part of code:

```c
yy7:
	yych = *++str;
	switch (yych) {
	case 't':	goto yy8;
	default:	goto yy6;
	}
yy8:
	++str;
	yych = *str;
	switch (yych) {
	case '\t':
	case ' ':	goto yy8;
	case ':':	goto yy10;
	default:	goto yy6;
	}
yy10:
	yych = *++str;
	switch (yych) {
	case 't':	goto yy14;
	default:	goto yy12;
	}
```
I generated code using `re2c.exe -W -Werror -o test.cc test.re` command. I also tried to add `-s` and `-b` switches, but they did not help. Attempt so use multiple re2c blocks or conditions also failed.

I played a bit with rules and found that rule `"Test" SWS { return 1; }` generates proper code, but `"Test" SWS "test"` not. So something bad happened when all these whitespace rules, somehow they are removed completely if something else follows them.

I am using re2c 0.16 on Cygwin x86_64, compiled with gcc 5.3.0.

**Comment by skvadrik** [comment]
I think the problem is that `SWS` doesn't match single space:
```
SWS
    = LWS?
    = ((WSP* CRLF) WSP+)?
    = ((SP | HTAB)* CR LF (SP | HTAB)+)?
    = ([\x20\x09]* "\r\n" [\x20\x09]+)?
```
So it either matches empty string or something that contains `\r\n` substring (single space is neither). Do you agree?

> I also tried to add -s and -b switches, but they did not help.

Actually, first thing you should check when you suspect that re2c generates incorrect code is skeleton: http://re2c.org/manual/features/skeleton/skeleton.html . Command line might look like `re2c -W -S -o test.cc test.re && gcc test.cc -o test && ./test`, no output means no errors. Skeleton cannot prove program correctness, but it can identify a whole class of code generation bugs.

**Comment by sirzooro** [comment]
Thanks for the skeleton hint, I will give it a try.
I found that I made a mistake in LWS, it should look this way: `LWS = (WSP* CRLF)? WSP+;` (I changed square brackets to round one and forgot to add question mark). So this is not an issue, you can close it.
