### ISSUE TITLE
Please add symbol name to "can't find symbol" error message

### ISSUE THREAD

**Issue by sirzooro** [skvadrik/re2c#147]
Please add symbol name to "can't find symbol" error message, it would allow to quickly spot what is wrong. Now we have to position cursor at given row and column to find that name.

**Comment by skvadrik** [comment]
Done, thanks for suggestion!

Github sometimes (but not every time) automatically closes bugs, probably because commit message is of the form "Fixed #...". This should be stopped.

**Comment by skvadrik** [comment]
It turns out, "Fixed #N" would trigger closing issue #N, but "Fixed bug #N" wouldn't. Most confusing. :)

**Comment by sirzooro** [comment]
Thanks! :)
