### ISSUE TITLE
Line number in #line directive after enum YYCONDTYPE is 0-based

### ISSUE THREAD

**Issue by sirzooro** [skvadrik/re2c#152]
As in title. Other `#line` directives seems to be correct, except that one - its value should be increased by one.

**Comment by skvadrik** [comment]
Please point at the wrong `#line` directive in the following example:
```
/*!types:re2c*/

/*!re2c
    <a> "a" { return 1; }
*/
```
Compile with `./re2c 1.re -c`:
```
/* Generated by re2c 0.16 on Tue Jun 28 18:55:41 2016 */
#line 1 "1.re"
#line 4 "<stdout>"

enum YYCONDTYPE {
        yyca,
};

#line 1 "1.re"


#line 13 "<stdout>"
{
        YYCTYPE yych;
        switch (YYGETCONDITION()) {
        case yyca: goto yyc_a;
        }
/* *********************************** */
yyc_a:
        if (YYLIMIT <= YYCURSOR) YYFILL(1);
        yych = *YYCURSOR;
        switch (yych) {
        case 'a':       goto yy4;
        default:        goto yy3;
        }
yy3:
yy4:
        ++YYCURSOR;
#line 4 "1.re"
        { return 1; }
#line 32 "<stdout>"
}
#line 5 "1.re"
```

**Comment by sirzooro** [comment]
Instead of `#line 1 "1.re"` should be `#line 2 "1.re"`

Please insert some C code between `/*!types:re2c*/` and `/*!re2c` block with will trigger warning or error during compilation, and compare line number in message with actual line number in `.re` file.

**Comment by skvadrik** [comment]
The bug you're talking about is probably fixed in HEAD (I have no way to confirm it since I don't have a faulty example). There is at least one related fix in `devel` branch (HEAD) which is not in `master` yet.

**Comment by sirzooro** [comment]
```c
/*!types:re2c*/

#warning this is line 3

void f()
{
/*!re2c
    <*> * {}
*/
}
```
When you will generate code and compile it, you will get:
```
linebug.re:2:2: warning: #warning this is line 3 [-Wcpp]
```
But it should be:
```
linebug.re:3:2: warning: #warning this is line 3 [-Wcpp]
```

**Comment by skvadrik** [comment]
Yep, fixed in HEAD. I'll add your example to test suite. :)

**Comment by sirzooro** [comment]
Good to hear :)

**Comment by skvadrik** [comment]
The good thing about re2c test suite is that we only test re2c-generated output (it should byte-to-byte coincide with reference output). Unlike C/C++ compiler results, re2c output is stable: we need to verify its correctness only once and then monitor all the changes.

**Comment by sirzooro** [comment]
OK, looks good.
