### ISSUE TITLE
Open text files with "wb" causes issues on Windows

### ISSUE THREAD

**Issue by pauloscustodio** [skvadrik/re2c#160]
After every run of re2c I get a warning in Visual Studio about "inconsistent line ending" on the generated files. The cause is the "b" in fopen(file_name, "wb") that opens the file in binary mode, and stdio does not write the correct line ending for Windows ("\r\n" instead of "\n" in Linux). In Linux the "b" flag has no effect.

The issue happens in two locations: output.cc:74 and output.cc:349

Can this be changed to fopen(file_name, "w")?

I can submit a PR if the answer is positive.

**Comment by skvadrik** [comment]
I think the tests will break on Windows: re2c will generate `\r\n` instead of `\n`, which is expected by reference test results. However, people can only run tests on Windows if they have Bash, which suggests that they use Cygwin or Mingw.

One test is broken (with `"w"` instead of `"wb"`)  if I build re2c with Mingw and test with Wine (on Linux).

Of course, re2c should generate correct line endings on Windows and the tests should account for that (substitute `\r\n` with `\n` in the generated code before comparing it against reference result).

So I expect the full fix to be:

- change `"wb"` to `"w"` in output.cc
- amend test script to patch line endings in the generated code

I'd be glad to accept your PR, but if you can't fix test script (don't have Bash or something), I can come up with my fix.

**Comment by skvadrik** [comment]
Ah, the test script already has it (run_tests.sh.in:174). I'll investigate why that single test breaks in Mingw builds.

**Comment by skvadrik** [comment]
It turns out that test script only patches stderr and stdout, while the generated output is written to file. We only recently started to use `-o` option for testing.

**Comment by skvadrik** [comment]
Too bad, some of the tests contain `\r\n` line endings (php20150211_parse_date_crlf.ig.re and php20140822_zend_language_scanner_crlf.igcd--flex-syntax.re), so now tests break on my platform. :)

**Comment by pauloscustodio** [comment]
Maybe the diff in run_tests.sh can be replaced by "diff -w" causing differences in whitespace to be ignored and the tests to pass.
That's what I had to do in my port of run_tests.sh to perl to run the tests on Windows. 

-------- Mensagem original --------De: skvadrik <notifications@github.com> Data: 05/11/16  15:05  (GMT+00:00) Para: skvadrik/re2c <re2c@noreply.github.com> Cc: pauloscustodio <pauloscustodio@gmail.com>, Author <author@noreply.github.com> Assunto: Re: [skvadrik/re2c] Open text files with "wb" causes issues on Windows (#160) 
Too bad, some of the tests contain \r\n line endings (php20150211_parse_date_crlf.ig.re and php20140822_zend_language_scanner_crlf.igcd--flex-syntax.re), so now tests break on my platform. :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/skvadrik/re2c","title":"skvadrik/re2c","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/skvadrik/re2c"}},"updates":{"snippets":[{"icon":"PERSON","message":"@skvadrik in #160: Too bad, some of the tests contain `\\r\\n` line endings (php20150211_parse_date_crlf.ig.re and php20140822_zend_language_scanner_crlf.igcd--flex-syntax.re), so now tests break on my platform. :)"}],"action":{"name":"View Issue","url":"https://github.com/skvadrik/re2c/issues/160#issuecomment-258617368"}}}

**Comment by skvadrik** [comment]
I fixed testing script and deleted tests which contained `\r\n` (they are duplicates with just line endings changed): https://github.com/skvadrik/re2c/commit/334c650bd33c45a21f8fb467d02b2b6cfda674e1

I can accept your fix (`"wb"` to `"w"`) now, otherwise I'll commit the changes myself.

**Comment by skvadrik** [comment]
> Maybe the diff in run_tests.sh can be replaced by "diff -w" causing differences in whitespace to be ignored and the tests to pass.

I think that `-w` is non-POSIX: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/diff.html, and we try to be mostly POSIX-compliant. Besides, some test results contain binary data which should be compared byte-to-byte (output of the `--skeleton` option).

Maybe you don't need `diff -w` after 334c650 ?

**Comment by pauloscustodio** [comment]
I've cherry-picked the change in output.cc into a new pull-request.

Thanks.

**Comment by skvadrik** [comment]
Fixed in https://github.com/skvadrik/re2c/pull/161.
