### ISSUE TITLE
Reading files with "rb" causes issues in Windows

### ISSUE THREAD

**Issue by pauloscustodio** [skvadrik/re2c#163]
This is a follow-on of #162.

The fix provided solves the test failures, but there is still an issue in the generated files on Windows. The output file has different line endings:
 - lines generated by re2c have the correct line ending CR-LF.
 - lines copied from the input .re file have CR-CR-LF, probably the first CR read verbatin from the input .re file, and the second CR produced by stdio while writing the end-of-line.

**Comment by skvadrik** [comment]
Do you mean that reading any file that has CR-LF line endings with `"rb"` and then writing it with `"w"` results in CR-CR-LF on Windows? Curious, but it does make sense that one should either use text mode or binary mode, but do it consistently (for both reading and writing).

In principle what is good enough for C/C++ compiler should be good enough for re2c: it doesn't expect any encoding-breaking input. I'll try dropping `"b"`.

**Comment by skvadrik** [comment]
We have some tests (namely, code_points.*.re) with binary input: regular expressions that contain string literals including all characters in one-byte range except newline.

These tests are broken on Windows by dropping `"b"` (I run re2c in Wine on Linux and get crash dumps). Which is quite expectable. These tests have been added to capture the exact behaviour of re2c lexer on all input characters that are accepted by lexical grammar.

It probably makes sense to restrict re2c to ASCII input.

**Comment by pauloscustodio** [comment]
> Do you mean that reading any file that has CR-LF line endings with "rb"
and then writing it
> with "w"results in CR-CR-LF on Windows?

Yes, that is correct. On reading with "rb" your text will include the CR-LF
at the end of each line. When writing with "w" the CR is output and then
the LF is translated by stdio to CR-LF,

> It probably makes sense to restrict re2c to ASCII input.

Another option is to use /\r?\n/ as end-of-line regular expression and
convert to a single '\n' when reading the .re file.

**Comment by skvadrik** [comment]
> Another option is to use /\r?\n/ as end-of-line regular expression and convert to a single '\n' when reading the .re file.

Yep. At least this way input will be the same on all platforms.

I've pushed a quick-and-dirty fix: https://github.com/skvadrik/re2c/commit/a51c7c858c99641d473bfbb375b082605f74f83b. A more elegant solution would perform conversion immediately wjhen CR LF is recognized by the lexer, but `devel` has some important fixes in lexer which I don't want to pull in `master` just yet.

**Comment by pauloscustodio** [comment]
The fix was not working. I simplified a bit and submitted a pull request,
but as I have an intermediate version with CMakeLists.txt, to able to build
and test on on MS-C++, you may need to cherry-pick.

Thanks.

**Comment by skvadrik** [comment]
Eh, I last-minute-fixed `!=` to `==`. Sorry.

Thanks for the patch.
