### ISSUE TITLE
re2c help message is too wide for most terminals

### ISSUE THREAD

**Issue by pmetzger** [skvadrik/re2c#176]
Howdy! The message you get when you run re2c --help is formatted for much wider than the standard 80 columns one finds on a normal terminal.

Fixing this is pretty easy, it just requires a quick reformat of conf/msg.cc. I might volunteer to do it if the change would be accepted.

**Comment by pskocik** [comment]
The  --help output should also be synced with the options section of the manpage. I believe it should be completely generated from that manpage section.
My https://github.com/skvadrik/re2c/pull/177
does just that.  (Ideally, that generation, as  well as syncing between the master branch and the gh-pages-gen branch should be made part of the build system, but I don't feel like playing with that).

**Comment by skvadrik** [comment]
Yes, manpage `doc/manpage.rst` definitely should be synced with `--help` and the corresponding online documentation page in `gh-pages-gen` branch should be synced with both. I just didn't find an elegant way to do it yet.

I  think `--help` must be the primary source as it is included in re2c source code.
