### ISSUE TITLE
Comment syntax?

### ISSUE THREAD

**Issue by pmetzger** [skvadrik/re2c#180]
I find myself wanting to comment my re2c grammar, but it isn't clear if there's any sort of text inside the re2c C comment block itself that won't be treated as though it is valid re2c code.

How can I do this cleanly? Is there some undocumented method?

**Comment by skvadrik** [comment]
Sure, both single-line comments `//` and multiliine comments `/* ... */` should work.

**Comment by skvadrik** [comment]
Also, if you want to comment the whole `/*!re2c ... */` block, the best way is just to put an extra space between `/*` and `!re2c`.

**Comment by pmetzger** [comment]
You can't put a /* ... */ inside a /* ... */ comment unfortunately, they don't nest.
But you're saying I should be able to put a // anywhere inside the comment block anywhere and that will not be a problem?

**Comment by pmetzger** [comment]
(And could that be documented?)

**Comment by skvadrik** [comment]
Well, inside of a re2c block you *can* have another multiline comment, but it will probably break your syntax highlighter. Single-line comments won't break syntax highlighter. Do you have an example of code that doesn't work?

As for documentation, I already added a reminder in #140.

**Comment by pmetzger** [comment]
Is the reason a multi-line comment will work that re2c preprocesses the c-like comments in the first place? Because C itself does not allow nested comments.

**Comment by skvadrik** [comment]
Yes. re2c parses C/C++ code, finds multiline comments of the form `/*!re2c ... */` (and a couple of variations) and parses the code inside of these comments.

This is the exact place in the re2c source code that handles nested multiline comments: https://github.com/skvadrik/re2c/blob/devel/re2c/src/ast/lex.re#L207, and this one handles single-line comments https://github.com/skvadrik/re2c/blob/devel/re2c/src/ast/lex.re#L204.

**Comment by pmetzger** [comment]
Cool! Thank you so much!
