### ISSUE TITLE
yych being set by YYPEEK () and then not used.

### ISSUE THREAD

**Issue by pmetzger** [skvadrik/re2c#182]
Howdy! Using the clang static analyzer and re2c 0.16, I've found a few instances where the analyzer finds instances of `yych = YYPEEK ();` where `yych` is not subsequently used in the control path. Although benign as bugs go, I'd still like to help you fix it.

Not 100% sure how to build a minimizing test case, without which it will be hard for you to track down the bug. Is there a way to figure out from the goto labels in the generated code to particular regular expressions that triggered the construction of that part of the code?

**Comment by skvadrik** [comment]
You can build a minimal test case using `--skeleton` option: http://re2c.org/manual/features/skeleton/skeleton.html
All it needs it regular expressions (everything inside of `/*!re2c ... */` blocks), all the interface code is generated automatically. You can make sure that skeleton program builds and still triggers the bug, then post your reduced example, command line and warning report here.

**Comment by pmetzger** [comment]
It seems to build! I'll try bisecting the code until I get a minimal instance.

**Comment by pmetzger** [comment]
Okay, it seems to work! I've produced what isn't quite a minimal instance but it retains all the original warnings I was getting from the clang static analyzer just in case they're somehow different versions of the bug.

Build the attached with:
`re2c --bit-vectors --nested-ifs -W -Werror --input custom --skeleton -o test-skeleton.c test-skeleton.re`

Then use `scan-build` or `ccc-analyzer` directly and you get:

>test-skeleton.c:299:9: warning: Value stored to 'yych' is never read
>        yych = YYPEEK ();
>        ^      ~~~~~~~~~
>test-skeleton.c:320:9: warning: Value stored to 'yych' is never read
>        yych = YYPEEK ();
>        ^      ~~~~~~~~~
>test-skeleton.c:376:9: warning: Value stored to 'yych' is never read
>        yych = YYPEEK ();
>        ^      ~~~~~~~~~
>3 warnings generated.
>scan-build: 3 bugs found.v

So far as I can tell, the errors are indeed correct.

I will attach test-skeleton.c directly just to make sure you have exactly the same one. (For some reason, github has insisted that I put .txt at the ends of the file names...)

[test-skeleton.re.txt](https://github.com/skvadrik/re2c/files/911533/test-skeleton.re.txt)
[test-skeleton.c.txt](https://github.com/skvadrik/re2c/files/911534/test-skeleton.c.txt)

**Comment by skvadrik** [comment]
Thank you for the detailed report!
The bug has already been fixed in `devel` branch (I don't recall it, but maybe there was a similar issue somewhere).

**Comment by pmetzger** [comment]
When is the next release version likely to be cut? It seems like there's a lot of good stuff queued up... :)

**Comment by skvadrik** [comment]
Quite a lot, more than a year of development.
Unfortunately the main change in the upcoming release requires some research: it involves a relatively novel algorithm with a few modifications of my own. I have formalize the algorithm, and it takes me longer than expected.

**Comment by pmetzger** [comment]
Cool. Is there any way to cherry pick the fixes for some of the other bugs, or is that too hard to do because they're dependent on the new algorithm for generating the automaton?

**Comment by skvadrik** [comment]
I suppose it's hard. The whole codebase changed since the last release.
I hope it won't be too long until the next release (a month?), but I said the same thing half a year ago and new sub-problems keep showing up.
