### ISSUE TITLE
Strange syntax error with parenthesized trailing context

### ISSUE THREAD

**Issue by pmetzger** [skvadrik/re2c#183]
This:

`D+ "." / "a"      {  }`

is parsed fine by re2c.

This (the same regexp, parenthesized):

`(D+ "." / "a")      {  }`

Results in a syntax error (at the `/`).

Is this expected behavior?

**Comment by skvadrik** [comment]
Yes, trailing context must be in top-level regular expression, and parenthesis make it nested.

**Comment by pmetzger** [comment]
Ah, but here is the problem.

Say you have a top level expression of the form:

`A | B | C    {}`

Note also that (at least in Flex) the `/` operator has *lower* precedence than the `|` operator.

You then get into a situation where

`a / b | c {}`

will get misparsed as `a` with trailing context `b|c` rather than as `a` with trailing context `b` vs. `c`.

The obvious solution is to do `(a / b)`, which doesn't place trailing context mid-expression but just fixes the parse. However, that blows up.

There's no documentation about the precedence of re2c regexp operators that I found, and in any case it is very natural for someone to want (for a human reader) to make sure that the intent is

`(a / b) | c  { ... }`

so perhaps there could be some way to figure out if the `( )` are surrounding a top level expression rather than an interior expression?

**Comment by pmetzger** [comment]
One workaround, I suppose, is to change

`(a / b) | c    { D }`

to the two lines

`a / b    { D }`
`c          { D }`

Perhaps for now a warning in the documentation would be suitable?

**Comment by skvadrik** [comment]
When I say "in top-level", I mean "not included in any alternative, concatenation or iteration". And this is the standard meaning of "top-level" as far as I know. Thus in `(a / b) | c` trailing context is not in top-level, as it is included in higher-level alternative.

In re2c `/` also has the lowest priority. And it can be used only once per rule.
 
The "workaround" you mentioned is indeed the proper way to express  `(a / b) | c`.

**Comment by skvadrik** [comment]
The thing I'm working on right now will allow to save cursor position on any level of regular expression, so that will allow you to have nested lookahead operator.
