### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by pmetzger** [skvadrik/re2c#184]
In the man page:

>       re2c:yyfill:enable = 1;
>              Set this to zero to suppress  generation  of  YYFILL  (n).  When
>              using this be sure to verify that the generated scanner does not
>              read behind input. Allowing this behavior might introduce  sever
>              security issues to you programs.

You probably want this to read:

>              Set this to zero to suppress  generation  of  YYFILL  (n).  When
>              using this**,** be sure to verify that the generated scanner does not
>              read **beyond** the **available** input. Allowing this behavior
>              might introduce **severe** security issues to **your** programs.

**Comment by skvadrik** [comment]
I believe @pskocik recently fixed it in `master`. It now reads as:

> Set this to zero to suppress the generation of YYFILL (n). When using this, be sure to verify that the generated scanner does not read behind the end of your input, allowing such behavior might introduce several security issues to your program.

However, if you think your variant is better, feel free to send a patch on top of `master`.
If you don't have time for that, in future please submit such minor documentation issues as a comment in #140.

**Comment by pmetzger** [comment]
I don't have time right now, but I'll put a comment in #140. I think my variant is better, I don't think "several" is correct (severe was meant) and I don't think "behind" is correct (beyond is clearly the intended word).

**Comment by skvadrik** [comment]
Thank you! I will close this issue as a duplicate then.
