### ISSUE TITLE
Build with "--enable-docs" fails

### ISSUE THREAD

**Issue by Ziris85** [skvadrik/re2c#194]
Good evening! I just tried compiling the latest point release version (**1.0.1**), and the one prior (**1.0.0**) and get the same trouble. Whenever I compile with the `--enable-docs` flag, the subsequent make command fails with:
```
rst2man ./doc/help.rst > src/conf/help.cc.1
./genhelp.sh src/conf/help.cc.1 src/conf/help.cc
make[1]: ./genhelp.sh: Command not found
make[1]: *** [src/conf/help.cc] Error 127
```
Indeed, there is no `genhelp.sh` file in the tarball:
```
]$ tar --exclude="*/*/*" -tzf re2c-1.0.1.tar.gz 
re2c-1.0.1/
re2c-1.0.1/aclocal.m4
re2c-1.0.1/examples/
re2c-1.0.1/NO_WARRANTY
re2c-1.0.1/Makefile.am
re2c-1.0.1/depcomp
re2c-1.0.1/bootstrap/
re2c-1.0.1/configure
re2c-1.0.1/install-sh
re2c-1.0.1/Makefile.in
re2c-1.0.1/config.h.in
re2c-1.0.1/missing
re2c-1.0.1/doc/
re2c-1.0.1/test-driver
re2c-1.0.1/compile
re2c-1.0.1/README
re2c-1.0.1/autogen.sh
re2c-1.0.1/CHANGELOG
re2c-1.0.1/run_tests.sh.in
re2c-1.0.1/src/
re2c-1.0.1/configure.ac
re2c-1.0.1/test/
```
Perhaps this is meant to be created on compile? Building without the flag seems to go through, with a message about rebuilding for the docs:
```
Reconfigure to rebuild docs: ./configure --enable-docs
```
Of course, is always nice to be able to generate documentation for use :)

**Comment by skvadrik** [comment]
Yep, I forgot to package this script, thanks for reporting!

> Of course, is always nice to be able to generate documentation for use :)

Documentation is *always* generated (from precompiled files) without ``--enable-docs`` (simple `make` is enough). This configure option is mostly used by re2c developers who change documentation source files and need to regenerate them.

**Comment by skvadrik** [comment]
The fix: https://github.com/skvadrik/re2c/commit/9a0b9603d24194efecdb41e7444ce926339dc674.

I will release 1.0.2 by the end of the week (after addressing some other documentation issues). Meanwhile, if you just want to *have* docs (and not change and *rebuld* them), configure without ``--enable-docs``.

**Comment by Ziris85** [comment]
You're welcome, and snap, I guess I misunderstood the purpose of that flag. Thanks for clarifying!
