### ISSUE TITLE
example Numbers result not match

### ISSUE THREAD

**Issue by TopN** [skvadrik/re2c#199]
example url: http://re2c.org/examples/example_01.html

```
$ ./integers 123 0xfF 010 0B101 ?
decimal
hexadecimal
octal
binary
error
```

On macOS Sierra result:

```
decimal
hexadecimal
octal
binary
decimal
```

My env:

```
$ re2c -v
re2c 1.0.3

$ g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by skvadrik** [comment]
Looks to me like the intended input bytes never reach the program: either your shell substituted ``?`` with something else, or an unusual encoding is used (the program expects ASCII, but should work with UTF-8 as well). I suggest the following:

* quote ``?`` as``'?'``
* run executable with ``LANG=C``
* check the input byte stream with ``echo -n '?' | hexdump -C`` or redirect to file and view file in binary --- make sure that ``?`` corresponds to `0x3f`
* if nothing helps and you are convinced that the fault is in re2c, try this program instead (it should be free of all environment side-effects on input strings), remove ``.txt`` suffix: 
[integers_v2.re.txt](https://github.com/skvadrik/re2c/files/1754189/integers_v2.re.txt)
* if still have the faulty behaviour for the above program, attach your generated ``.cc`` file and run ``re2c -S integers_v2.re -o integers_v2.cc && g++ integers_v2.cc -o integers_v2 && ./integers_v2`` (output should be empty)

**Comment by TopN** [comment]
hi, skvadrik thanks for your help. 

i had try the next in my environment：

```
$ echo -n '?' | hexdump -C
00000000  3f                                                |?|
00000001

$ ./01_recognizing_integers '?'
error

$ ./01_recognizing_integers ?
decimal

$ LANG=C ./01_recognizing_integers ?
decimal

$ LC_ALL=C ./01_recognizing_integers ?
decimal
```

I also try integers_v2.re.txt, and get the right result:

```
$ ./integers_v2
decimal
hexadecimal
octal
binary
error
```

**Comment by skvadrik** [comment]
Eh, I never realized that ``?`` in POSIX shell matches any one-symbol filename. Quotes should fix the problem for you. :)

http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html
> 2.13.1 Patterns Matching a Single Character
> When unquoted and outside a bracket expression, the following three characters shall have special meaning in the specification of patterns:
?
    A question-mark is a pattern that shall match any character.

**Comment by TopN** [comment]
Thanks for your help. :)
