### ISSUE TITLE
Option re2c:flags:input not working

### ISSUE THREAD

**Issue by Durimar** [skvadrik/re2c#202]
Hello.
I can't enable 'custom' input mode.

//-- test.re - start ----------------------
```
/*!re2c
    re2c:flags:input = 'custom';
*/
```
//-- test.re - end -----------------------

D:\re2c.exe test.re
re2c: error: line 2, column 9: bad configuration value (expected: 'default', 'custom')

Thanks.

**Comment by skvadrik** [comment]
Hi! `custom` is considered a keyword here, not a string, so re2c expects it without quotes:
```
/*!re2c
    re2c:flags:input = custom;
*/
```
The above does work. I realize this might be confusing, so it's probably worth recognizing keywords in quotes as well as without quotes.
