### ISSUE TITLE
C++98 example fails to generate

### ISSUE THREAD

**Issue by rorlork** [skvadrik/re2c#205]
I was trying to use the example as a starting point, but when trying to generate the C file from it the following error is returned by re2c

`re2c : error : line 116, column 32: define 'define:YYCURSOR' already being used and cannot be changed`

as far as I can tell this is because in line 100, YYCURSOR is defined as s:

```		re2c:define:YYCURSOR = s;```

and then in line 116 it's trying to redefine it as in.cur:

```		re2c:define:YYCURSOR = in.cur;```

From what I've seen in the documentation, this should be working fine, we should be allowed to re-define things in different blocks.

**Comment by rorlork** [comment]
Okay you are right. I forgot I was using a version that was made to compile in visual studio, from https://github.com/wjk/re2c-win32 and that is from version 0.14.3 of the lexer. Sorry for the misunderstanding, I'll close the issue and upgrade to that.

**Comment by skvadrik** [comment]
No worries. :)
