### ISSUE TITLE
wrong long option for -c mode

### ISSUE THREAD

**Issue by fbenkstein** [skvadrik/re2c#206]
The long option for `-c` is wrong in the documentation pretty much everywhere.  It's documented as `--conditions` but it's actually `--start-conditions`.  I suggest accepting both and also adding a hint in the documentation like "Up until <release-version> this option was only accepted in the `--start-conditions` variant even though the documentation called it `--conditions`.

https://github.com/skvadrik/re2c/blob/36737173bf08b885ed52a58051e1eeb2e68cd3f0/re2c/src/conf/parse_opts.re#L138

**Comment by skvadrik** [comment]
Fixed: https://github.com/skvadrik/re2c/commit/25c327f5987ae043542a21442450d6489bd0b0c6. Thanks for reporting!
