### ISSUE TITLE
make generic API more generic

### ISSUE THREAD

**Issue by lego12239** [skvadrik/re2c#207]
Hi.

It would be great if re2c generate "YYPEEK(&yych);" instead of "yych = YYPEEK();". In this case,
we can in addition to default variant:

#define YYPEEK(yych) *yych = *pos

do something like this:

#define YYPEEK(yych) if (pos == end) { fill(); } *yych = *pos

**Comment by skvadrik** [comment]
Closing, as the `YYPEEK` API is fixed and cannot be changed to avoid breaking backwards compatibility.

Note that it is possible to use ternary operator in `YYPEEK`, as demonstrated in this example: http://re2c.org/manual/manual_c.html#custom-checks. I guess this can somehow be combined with comma operator to call `fill`.
