### ISSUE TITLE
re2c -V crashes (was re2c 1.1 fails with spamassassin 3.4.1 (sa-compile) / perl 5.28.0)

### ISSUE THREAD

**Issue by danielluke** [skvadrik/re2c#214]
% sa-compile -D
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
/opt/perlbrew/perls/perl-5.28.0/bin/sa-compile requires re2c for proper operation.

re2c 1.0.3 works fine.

I haven't investigated this any further (yet).

**Comment by danielluke** [comment]
on Mac OS X 10.13.6

**Comment by pmetzger** [comment]
I don't know that this provides enough information to reproduce the problem.

**Comment by danielluke** [comment]
re2c -V crashes (which is what causes sa-compile to fail).

**Comment by pmetzger** [comment]
I can reproduce that.

**Comment by danielluke** [comment]
commenting out the test in sa-compile lets it run successfully.

**Comment by pmetzger** [comment]
This clearly needs fixing though. Nothing should cause a properly behaving program to dump core. I note that the test suite passes without incident.

**Comment by pmetzger** [comment]
@danielluke Could you change the issue title to "re2c -V crashes" or some such?

**Comment by danielluke** [comment]
I wanted to leave the spamassassin stuff in there since I expect others to see this issue and spamassassin is pretty widely used (hopefully it will appear in searches and help others out).

**Comment by skvadrik** [comment]
Can you please check the yesterday's fix in master? https://github.com/skvadrik/re2c/commit/348d8689beaa749a18d394a103335d2c64f7b8b4

**Comment by skvadrik** [comment]
I will release 1.1.1 soon, just need to sort out a couple of related things.

**Comment by danielluke** [comment]
1.1 with the patch from that change seems to work: 

% ./re2c -V
010100

**Comment by pmetzger** [comment]
That patch fixes it.

**Comment by skvadrik** [comment]
Released 1.1.1. Closing the issue.
