### ISSUE TITLE
variable length trailing context is included in tokens

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#22]
Example:

/*!re2c

("a"|"b")/[1]    { return KEYWORD; }
("a"|"b")/[0-9]\+ { return KEYWORD; }
[0-9]\+           { return NUMBER;  }

*/

Scanning over "a77 a1 b8 b1" one would expect the
following:
1: KEYWORD = "a"
2: NUMBER  = "77"
3: KEYWORD = "a"
4: NUMBER  = "1"
5: KEYWORD = "b"
6: NUMBER  = "8"
7: KEYWORD = "b"
8: NUMBER  = "1"

Instead re2c scanner returns:
1: KEYWORD = "a77" (!)
2: KEYWORD = "a"
3: NUMBER  = "1"
4: KEYWORD = "b8"  (!)
5: KEYWORD = "b"
6: NUMBER  = "1"

Full test case is attached.

Original comment by: alder

**Comment by linuxjackto1** [comment]
thanks www.movied.org
