### ISSUE TITLE
Piece of code saving a backtracking point not generated

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#23]
re2c generates a wrong code that doesn't initialize 
YYMARKER in case the backtrack point is the very first 
character of the input. The attached patch fixes this 
problem.

Use the following script to reproduce the problem.

--test.re
/*!re2c
ALNUM = [0-9a-zA-Z];
ANY = [\000-\377];

"?!" ALNUM* {
}

"?" ALNUM+ {
}

(ANY\"?")* {
}
*/
--test.re--

Before patching (original): 
$ re2c test.re | grep "YYMARKER"
YYCURSOR = YYMARKER;

After patching:
$ re2c test.re | grep "YYMARKER"
YYMARKER = YYCURSOR + 1;
YYCURSOR = YYMARKER;

Original comment by: moriyoshi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
