### ISSUE TITLE
Missing forward declaration

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#24]
Getting the following error while trying to compile 
re2c on Fedora Core 5.

parser.y: In function 'int yyparse()':
parser.y:87: error: 'mkAlt' was not declared in this 
scope
parser.y:114: error: 'mkAlt' was not declared in this 
scope
parser.y:138: error: 'mkAlt' was not declared in this 
scope
make[1]: *** [parser.o] Error 1
make[1]: Leaving directory `/tmp/re2c-0.10.1'
make: *** [all] Error 2

Original comment by: czachary

**Comment by linuxjackto1** [comment]
thanks www.movied.org
