### ISSUE TITLE
re2c output is not atomic

### ISSUE THREAD

**Issue by terpstra** [skvadrik/re2c#245]
When I run this command and then interrupt it:
re2c -8 --no-generation-date src/symbol.re -o src/symbol.cpp

It will create an empty symbol.cpp file. This is problematic for make because the output now exists and so the job does not get rerun. To work around it, I must do this:

%.cpp:	%.re
	re2c -8 --no-generation-date $< > $@.tmp
	mv $@.tmp $@

However, it would be nicer if '-o' did this internally.

**Comment by skvadrik** [comment]
Yes, this seems useful. The question is, how to create a temporary file portably in C++98?

One possible way is to open `filename.tmp` in the output directory (the name can be made a bit more random, e.g. to include timestamp) and fail if the file already exists. For that I think we can use `open` with `O_EXCL` on POSIX systems (which should cover Unixes, BSDs and macOS) and `_open` with `_O_CREAT|_O_EXCL` on Windows.

Out of curiosity, is your output file large? It seems that in most cases re2c does not take that long to generate output.

**Comment by terpstra** [comment]
My re2c output is 944kB. More relevant, however, is it takes 13 seconds to run... and re2c seems to open the file fairly early in the process.

**Comment by terpstra** [comment]
FYI, we will be open sourcing our tool which used re2c (wake) in the next few months, so you can see what all my complaining was driving towards. ;)

**Comment by skvadrik** [comment]
That's really good --- 13s sounds way too long, and I hope it can be reduced.

**Comment by skvadrik** [comment]
Pushed a fix: https://github.com/skvadrik/re2c/commit/2d30bc156610b44bd9f1be75f369bd34493efc11, let's see how it works. Thanks to [tmpfileplus](https://www.di-mgt.com.au/c_function_to_create_temp_file.html) for inspiration.
