### ISSUE TITLE
Large input example is not valid C

### ISSUE THREAD

**Issue by ruimaciel** [skvadrik/re2c#249]
While browsing through re2c's examples I've noticed that the [large input example](http://re2c.org/examples/example_03.html) is not valid C, and in fact appears to be non-idiomatic C++ that calls some C functions, which ends up being the worse of both worlds.

Furthermore, it would be helpful if the examples stated the versions of all technologies used in the example (i.e., re2c, C or C++, compiler, etc).

**Comment by skvadrik** [comment]
Well, as [this page](http://re2c.org/examples/examples.html) states:

> All examples are written in C-90 and in C++98

The one you pointed at is C++98. It may not be modern/idiomatic C++, but re2c examples are not a C++ tutorial. Re2c users are free to choose any flavour of C/C++ they like. It's the strong point of re2c.

Besides, everyone has their own idea of what idiomatic C++ is. For example, I don't share your opinion that using C library from C++ is "worse of both worlds". I do not want to impose my tastes on re2c users, but any choice of C++ flavour (or even formatting) would please some and displease the others.

> Furthermore, it would be helpful if the examples stated the versions of all technologies used in the example (i.e., re2c, C or C++, compiler, etc).

I agree that it would help to mention lower bound for re2c version in examples that use various options. However, as examples do not require modern C/C++, I don't think it's necessary to mention compiler versions. Snippets are biased towards GCC, which may be annoying for Clang/MSVC/etc. users, but I don't see how to rewrite them in a way that suits everyone.

**Comment by ruimaciel** [comment]
> The one you pointed at is C++98. It may not be modern/idiomatic C++, but re2c examples are not a C++ tutorial. Besides, everyone has their own idea of what idiomatic C++ is. For example, I don't share your opinion that using C library from C++ is "worse of both worlds".

That's not the point.  The point is that the example is C code written in C++, which wouldn't pass C++ code reviews from the last decade or so and is currently used as a tech demonstration of re2c.

It would be trivial to take the path of least resistance and refactor the example to standard C.  This is quite straight-forward as it requires simply doing away with the unnecessary class (i.e., refactoring the constructor and `bool input_t::fill(size_t)` into functions).

> Besides, everyone has their own idea of what idiomatic C++ is. 

Some aspects are less subjective than others.  For instance, using `malloc`, `memmove`, and `fread` in C++ has been a really bad code smell since the very start of C++, as it misses the whole point of C++ (RAII and the STL, for example).  There's no way around it. You'd be hard pressed to find anyone versed in C++ that would argue in favor of that.

**Comment by neil-edelman** [comment]
I don't know about idiomatic C++, but in the MACRO, it doesn't recognise comments; it will fail for:
#define thing /*
*/ thing

**Comment by technosaurus** [comment]
I think OPs point is:
Don't name files *.c when they contain c++ code.

**Comment by trofi** [comment]
The examples have changed. Link is 404 now.
