### ISSUE TITLE
re2c can not be built on fedora-5

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#25]
After just downloading it (v. 0.10.1), untarring, in
the end of ./configure && make I'm receiving:

---
make  all-am
make[1]: Entering directory
`/var/spool/ecbuild/RPM/BUILD/re2c-0.10.1'
if g++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -MT
code.o -MD -MP -MF ".deps/code.Tpo" -c -o code.o code.cc; \
then mv -f ".deps/code.Tpo" ".deps/code.Po"; else rm -f
".deps/code.Tpo"; exit 1; fi
if g++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -MT dfa.o
-MD -MP -MF ".deps/dfa.Tpo" -c -o dfa.o dfa.cc; \
then mv -f ".deps/dfa.Tpo" ".deps/dfa.Po"; else rm -f
".deps/dfa.Tpo"; exit 1; fi
if g++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -MT
main.o -MD -MP -MF ".deps/main.Tpo" -c -o main.o main.cc; \
then mv -f ".deps/main.Tpo" ".deps/main.Po"; else rm -f
".deps/main.Tpo"; exit 1; fi
if g++ -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -MT
parser.o -MD -MP -MF ".deps/parser.Tpo" -c -o parser.o
parser.cc; \
then mv -f ".deps/parser.Tpo" ".deps/parser.Po"; else
rm -f ".deps/parser.Tpo"; exit 1; fi
parser.y: In function âint yyparse()â:
parser.y:87: error: âmkAltâ was not declared in this scope
parser.y:114: error: âmkAltâ was not declared in this scope
parser.y:138: error: âmkAltâ was not declared in this scope
make[1]: *** [parser.o] Error 1
make[1]: Leaving directory
`/var/spool/ecbuild/RPM/BUILD/re2c-0.10.1'
make: *** [all] Error 2

---

Original comment by: sergey57

**Comment by linuxjackto1** [comment]
thanks www.movied.org
