### ISSUE TITLE
make check fails on windows

### ISSUE THREAD

**Issue by isuruf** [skvadrik/re2c#252]
On x86-64 systems, linux make check fails in last stable release. (With latest master, linux passes)
With MinGW-w64 x86_64, make check fails as well. https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/26418003#L1462

**Comment by skvadrik** [comment]
Hmm... the failed tests are those that use ``-t`` option (or the corresponding configuration) and generate a header file. These tests are not new --- my guess would be that something went wrong with scripting or filenames.

Could you show me the failed test artifacts? The easiest way to do so is to run the `run_tests.sh` script (with `-j1` just to eliminate any data races) in the build directory and archive the temporary directory created by it (prefixed with `test_`), and attach the archive here.

**Comment by skvadrik** [comment]
Can't reproduce after nearly a year, so closing the bug.
