### ISSUE TITLE
Turn off re2c:eof = 0

### ISSUE THREAD

**Issue by terpstra** [skvadrik/re2c#254]
I have a .re file with several different lexers in it.

Some of them use the new 're2c:eof = 0' feature. However, some of them use the 'sentinel method' with no need to YYFILL. As far as I can tell, once you turn on 're2c:eof = 0', it stays on for the rest of the file. I worked around this by putting all my 'sentinel method' lexers at the top of the file and then all the 'EOF rule' parsers at the bottom. 

If there is already a method 'unset' EOF mode, it should be documented somewhere. If there is not, it should be added.

**Comment by skvadrik** [comment]
All true, well spotted!

I added the ability to reset `re2c:eof` by setting it to a negative value `-1`, and updated the manpage and online docs (search for `re2c:eof` description among other configurations).

**Comment by terpstra** [comment]
Great!

**Comment by skvadrik** [comment]
Released re2c-1.2.1 with the fix. Closing the bug.
