### ISSUE TITLE
Add MSVC support

### ISSUE THREAD

**Issue by certik** [skvadrik/re2c#257]
In https://github.com/conda-forge/re2c-feedstock/pull/5, we got all of re2c to build with MSVC 2015, but there is a failure at link time, it can't find some files on Azure. On Appveyor, it can't find "ld" (https://ci.appveyor.com/project/conda-forge/re2c-feedstock/builds/26655531/job/6y5xmif44imor5y5). Both of these errors would almost for sure go away if re2c switched to cmake (#244). I think it's too hard to try to fix these errors with autotools.

Would you be interested in supporting MSVC?

**Comment by trofi** [comment]
> On Appveyor, it can't find "ld"

Sounds like a toolchain bug in the build environment. Looking at the `config.log` might help.

**Comment by skvadrik** [comment]
@certik , I myself am no cmake expert, and I don't have the bandwidth for it at the moment. But if you are willing to contribute a working cmake build system to re2c, I will merge it and do my best to maintain it (perhaps it will coexist with autotools for a while). There is some useful discussion and a more or less full list of requirements in https://github.com/skvadrik/re2c/issues/244. I realize the importance for MSVC users.

The problem in the build log seems unrelated to autotools vs cmake argument (linker is not found).

**Comment by skvadrik** [comment]
CMake build system has been added: https://github.com/skvadrik/re2c/pull/275, closing the bug.

**Comment by certik** [comment]
@skvadrik thanks! That's exciting. I'll try to port the Conda package to use MSVC now.

**Comment by skvadrik** [comment]
@certik It's all thanks to @ligfx, I only merged the pull request. :)

**Comment by certik** [comment]
Thanks @ligfx !
