### ISSUE TITLE
Segfault when parsing strings with umatched '

### ISSUE THREAD

**Issue by certik** [skvadrik/re2c#259]
Here is a reproducible example `segfault.re`:
```c++
#include <string>
#include <stdio.h>

enum num_t { ERR, BIN, OCT, DEC, HEX, STR };

static num_t lex(const char *YYCURSOR)
{
    const char *YYMARKER;
    /*!re2c
        re2c:define:YYCTYPE = char;
        re2c:yyfill:enable = 0;

        end = "\x00";
        bin = '0b' [01]+;
        oct = "0" [0-7]*;
        dec = [1-9][0-9]*;
        hex = '0x' [0-9a-fA-F]+;
        sstr = "'"  [^']* "'";

        *       { return ERR; }
        bin end { return BIN; }
        oct end { return OCT; }
        dec end { return DEC; }
        hex end { return HEX; }
        sstr end { return STR; }
    */
}

int main(int argc, char **argv)
{
    std::string s;
    //s = "334"; // Works
    s = "'"; // Segfault / wrong read in valgrind
    switch (lex(s.c_str())) {
        case ERR: printf("error\n"); break;
        case BIN: printf("binary\n"); break;
        case OCT: printf("octal\n"); break;
        case DEC: printf("decimal\n"); break;
        case HEX: printf("hexadecimal\n"); break;
        case STR: printf("str\n"); break;
    }
    return 0;
}
```
Compile and run:
```
$ re2c segfault.re -o a.cpp && g++ -g a.cpp && valgrind ./a.out
==12442== Memcheck, a memory error detector
==12442== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==12442== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==12442== Command: ./a.out
==12442== 
==12442== Conditional jump or move depends on uninitialised value(s)
==12442==    at 0x108AE6: lex(char const*) (a.cpp:76)
==12442==    by 0x108CBD: main (segfault.re:34)
==12442== 
==12442== Invalid read of size 1
==12442==    at 0x108AD9: lex(char const*) (a.cpp:74)
==12442==    by 0x108CBD: main (segfault.re:34)
==12442==  Address 0x1fff001000 is not stack'd, malloc'd or (recently) free'd
==12442== 
==12442== 
==12442== Process terminating with default action of signal 11 (SIGSEGV)
==12442==  Access not within mapped region at address 0x1FFF001000
==12442==    at 0x108AD9: lex(char const*) (a.cpp:74)
==12442==    by 0x108CBD: main (segfault.re:34)
==12442==  If you believe this happened as a result of a stack
==12442==  overflow in your program's main thread (unlikely but
==12442==  possible), you can try to increase the size of the
==12442==  main thread stack using the --main-stacksize= flag.
==12442==  The main thread stack size used in this run was 16777216.
==12442== 
==12442== HEAP SUMMARY:
==12442==     in use at exit: 0 bytes in 0 blocks
==12442==   total heap usage: 1 allocs, 1 frees, 72,704 bytes allocated
==12442== 
==12442== All heap blocks were freed -- no leaks are possible
==12442== 
==12442== For counts of detected and suppressed errors, rerun with: -v
==12442== Use --track-origins=yes to see where uninitialised values come from
==12442== ERROR SUMMARY: 79 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

Note 1: When a valid input is presented:
```diff
--- a/segfault.re
+++ b/segfault.re
@@ -29,8 +29,8 @@ static num_t lex(const char *YYCURSOR)
 int main(int argc, char **argv)
 {
     std::string s;
-    //s = "334"; // Works
-    s = "'"; // Segfault / wrong read in valgrind
+    s = "334"; // Works
+    //s = "'"; // Segfault / wrong read in valgrind
     switch (lex(s.c_str())) {
         case ERR: printf("error\n"); break;
         case BIN: printf("binary\n"); break;
```
Then one gets a clean valgrind run (no segfault, no invalid reads from memory):
```
$ re2c segfault.re -o a.cpp && g++ -g a.cpp && valgrind ./a.out
==12636== Memcheck, a memory error detector
==12636== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==12636== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==12636== Command: ./a.out
==12636== 
decimal
==12636== 
==12636== HEAP SUMMARY:
==12636==     in use at exit: 0 bytes in 0 blocks
==12636==   total heap usage: 2 allocs, 2 frees, 73,728 bytes allocated
==12636== 
==12636== All heap blocks were freed -- no leaks are possible
==12636== 
==12636== For counts of detected and suppressed errors, rerun with: -v
==12636== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

So this looks like a bug in re2c. Any ideas how one can fix that (even if just using a workaround)? I cannot control the input, and if the user presents a string that doesn't have a matching `'`, then this leads to a random segfault in my bigger application. I guess one workaround would be to pre-process the string to ensure that all `'` are matching.

Note 2: this is just a minimal modification of [examples/01_recognizing_integers.i.re](https://github.com/skvadrik/re2c/blob/7648f8dd9eaee660ca85a003e7246ede7b987e63/examples/01_recognizing_integers.i.re):
```diff
--- a/examples/01_recognizing_integers.i.re
+++ b/examples/01_recognizing_integers.i.re
@@ -1,6 +1,7 @@
+#include <string>
 #include <stdio.h>
 
-enum num_t { ERR, BIN, OCT, DEC, HEX };
+enum num_t { ERR, BIN, OCT, DEC, HEX, STR };
 
 static num_t lex(const char *YYCURSOR)
 {
@@ -14,25 +15,29 @@ static num_t lex(const char *YYCURSOR)
         oct = "0" [0-7]*;
         dec = [1-9][0-9]*;
         hex = '0x' [0-9a-fA-F]+;
+        sstr = "'"  [^']* "'";
 
         *       { return ERR; }
         bin end { return BIN; }
         oct end { return OCT; }
         dec end { return DEC; }
         hex end { return HEX; }
+        sstr end { return STR; }
     */
 }
 
 int main(int argc, char **argv)
 {
-    for (int i = 1; i < argc; ++i) {
-        switch (lex(argv[i])) {
-            case ERR: printf("error\n"); break;
-            case BIN: printf("binary\n"); break;
-            case OCT: printf("octal\n"); break;
-            case DEC: printf("decimal\n"); break;
-            case HEX: printf("hexadecimal\n"); break;
-        }
+    std::string s;
+    //s = "334"; // Works
+    s = "'"; // Segfault / wrong read in valgrind
+    switch (lex(s.c_str())) {
+        case ERR: printf("error\n"); break;
+        case BIN: printf("binary\n"); break;
+        case OCT: printf("octal\n"); break;
+        case DEC: printf("decimal\n"); break;
+        case HEX: printf("hexadecimal\n"); break;
+        case STR: printf("str\n"); break;
     }
     return 0;
 }
```

**Comment by skvadrik** [comment]
Hi @certik ! The problematic rule `"'"  [^']* "'"` allows terminating `NULL` in the middle of the single-quoted string. The lexer consumes the first single quote, and then nothing prevents it from consuming the following `NULL` as a part of the greedy lexeme. The fix is to exclude `NULL`: `"'"  [^'\x00]* "'"`.

If you need to handle strings with `NULL`, this is also possible, but you'll need a more complex [EOF handling method](http://re2c.org/manual/manual.html#eof-handling) (either bounds checking with padding or EOF rule).

**Comment by certik** [comment]
@skvadrik thanks a lot! That fixed it (https://gitlab.com/lfortran/lfortran/merge_requests/249/diffs).

I like using the NULL EOF method, as it's simple and fast. In terms of the rules to think about ---- when one does `[^...]`, then one must always include `[^...\x00]`, because otherwise the rule would consume NULL, and we need to reserve that only for the EOF handling. Is there any other catch like this? It seems everything else should be safe.

**Comment by skvadrik** [comment]
> I like using the NULL EOF method, as it's simple and fast.

Right, the sentinel method is the fastest one, so it should be used when possible.

> when one does `[^...]`, then one must always include `[^...\x00]`

More precisely,with the sentinel method (the case of `yyfill:enable = 0;`) `NULL` must NOT be allowed anywhere in the middle of lexeme (it can only be the terminating symbol). Repetition of negated class is just an example where it is easy to forget to exclude `NULL`. You can do something like this (and use `any` in other lexemes as well):

```
    any = [^\x00];
    q = ['];
    sstr = q (any \ q) q;
```

> Is there any other catch like this? It seems everything else should be safe. 

Hard to say! There are some common pitfalls like not handling default rule `*`, but this is captured by `-W` (warnings) and emphasized in all examples. There are many ways to get buffer refilling incorrect (particularly in the case of bounds checking with padding), but this is now mitigated with EOF rule and examples in the documentation (I hope so). I can say for sure that in re2c own lexer (which is a complex one) quite a few hidden rare-case segfaults have been found and fixed after using the AFL fuzzer (American Fuzzy Lop). All of them occurred on unexpected and invalid input, so it is worth having tests for those cases.

**Comment by certik** [comment]
@skvadrik thanks for the information. I am going to close this issue, as I think it's clear why it is happening and how to fix it.

I wonder if there is a way for re2c to ensure that all the rules (lexemes) in the file do not include `NULL` if `yyfill:enable = 0;` is used. For example for the `[^']` case I think it should be easy for re2c to figure out that I forgot to exclude `NULL`.

**Comment by skvadrik** [comment]
@certik Indeed re2c can check that `NULL` is not allowed in the middle of the rule, but there is no way to know which particular symbol is used as a sentinel (only the user knows it). For example, the input string can be `0xff`-terminated, and then `0xff` must be excluded from the range.

It may be possible to add a configuration `re2c:sentinel` which would be analogous to `re2c:eof`, but with no effect on code generation --- it would only check that the specified symbol does not occur in the middle of the rule. In cases when`re2c:yyfill:enable = 0;` is used re2c could give a warning to remind the users of `re2c:sentinel` option.

**Comment by certik** [comment]
@skvadrik yes, I think that's a great idea. That way re2c would ensure that the generated code won't segfault like mine did.

**Comment by skvadrik** [comment]
Ok @certik I opened a new bug #260 for it.
