### ISSUE TITLE
re2c creates an infinite loop

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#26]
The following code produces an infinte loop. 
(YYCURSOR is not incremented)

/*!re2c
[^\n\000]* '\n'    { do_this(); }
[^\n\000]* '\000'  { do_that(); }
*/

while this equivalent notation works:

/*!re2c
[^\n\000]* '\n'    { do_this(); }
[^\n\000]\+ '\000'  { do_that(); }
'\000'  { do_that(); }
*/

Original comment by: *anonymous

**Comment by linuxjackto1** [comment]
thanks www.movied.org
