### ISSUE TITLE
check that sentinel is not allowed in the middle of the rule

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#260]
See #259. Currently nothing prevents re2c users from making rules like `['] [^']* [']` when matching `NULL`-terminated strings. Forgetting to exclude `NULL` from the range `[^']` results in reads past the end of buffer and crashes.

Add configuration `re2c:sentinel` which would check that the specified symbol does not occur in the middle of the rule. In cases when `re2c:yyfill:enable = 0;` is used re2c should give a warning to remind the users of `re2c:sentinel` option.

**Comment by skvadrik** [comment]
@certik This has been fixed as of commit https://github.com/skvadrik/re2c/commit/de63b8baeda0acd2149bfe49ce0d713bf929d159. By default, re2c assumes that the sentinel is zero (to reduce the amount of noise on existing code). I also updated the docs: http://re2c.org/manual/manual.html#wsentinel-in-midrule

**Comment by skvadrik** [comment]
> In your opinion, does this make the sentinel method 100% safe now?

Eh, I would not call anything 100% safe as long as it is related to programming. :D 

But the new warning should catch the most common class of errors. It may not trigger in a very rare case when (1) `re2c:sentinel` is not used, (2) the chosen sentinel is non-zero, (3) it does occur in the middle of the rule, and (4) at the same time zero does not. Initially I intended to give warning always when `re2c:sentinel` is not set, but then I ran it on re2c test suite and realized that this will create a lot of noise, and many developers might be tempted to silence the warning.

**Comment by skvadrik** [comment]
@certik Do you mind if I add lfortran's lexer to re2c test suite, as it makes a really good real-world test case?

**Comment by skvadrik** [comment]
@certik Sure I can wait until the lexer becomes more stable!

With regard to uncertainty in the grammar, it seems that the variant where `return` is used as an identifier should be considerably more rare. In that case it might be better to use backtracking LR instead of GLR: always try the more likely `return`-as-keyword alternative first, and if that fails, try the less likely `return`-as-identifier alternative. At least this will avoid GLR overhead on "sane" code. But it is not available in bison --- I personally encountered it in [basil](https://www.lazycplusplus.com/basil/) (used to generate a C++ parser) and later in [this paper](http://research.cs.queensu.ca/home/cordy/Papers/TC_CASCON_Parsing.pdf). It would be great to have it as an option is bison.

**Comment by certik** [comment]
@skvadrik thanks for the suggestion. I'll look into that. My plan is to finish the full grammar with Bison GLR to get something working, and then see what could speed it up. With Basil I am a bit worried that it might need some maintenance (last release from 2002), which I don't mind doing, but only after I have something working first.

**Comment by skvadrik** [comment]
@certik Right, my comment was just to mention the backtracking LR approach in general.
