### ISSUE TITLE
Broken release link

### ISSUE THREAD

**Issue by sergeyklay** [skvadrik/re2c#262]
Hello,

Our automatic build system have a code similar to following:

```sh
pkgname=re2c
source="https://github.com/skvadrik/${pkgname}/releases/download/${RE2C_VERSION}/${pkgname}-${RE2C_VERSION}.tar.gz"
downloaddir="${HOME}/.cache/${pkgname}/${pkgname}-${RE2C_VERSION}"
prefix="${HOME}/.local/opt/${pkgname}/${pkgname}-${RE2C_VERSION}"
bindir="${prefix}/bin"

# ...

curl -sSL "$source" -o "${pkgname}-${RE2C_VERSION}.tar.gz"
```

This produces a command like this:
```
curl -sSL https://github.com/skvadrik/re2c/releases/download/1.2.1/re2c-1.2.1.tar.gz
```

Notice `.tar.gz`.

Since 1.2.0 this was broken because extension now is `.tar.xz`. Is there any reason to break automatic build systems? What problem you solved by changing file name format? Why this not reflected in the change log (as it affect package maintainers)?

**Comment by skvadrik** [comment]
Hi, sorry to break you workflow. Now that you have found the broken link, is it difficult for you to switch to .xz?

> What problem you solved by changing file name format?

See this bug: https://github.com/skvadrik/re2c/issues/221

> Why this not reflected in the change log (as it affect package maintainers)?

It is in the changelog for 1.2 (http://re2c.org/releases/changelog/changelog.html or just `fgrep '.xz' CHANGELOG`), but not in the release notes --- I underestimated the importance of the change for package maintainers.

**Comment by sergeyklay** [comment]
Well, no, it's not so difficult actually. Apologies for the too direct language! The main purpose of this issue is to point a problem. However, as I understand, it's well known and planned change. Thank you for the clarification. I'm closing this issue and again I am sorry about my tone.

**Comment by skvadrik** [comment]
No worries. :) It's good to realize that this kind of change may be problematic.
