### ISSUE TITLE
Some examples do not compile "out of the box"

### ISSUE THREAD

**Issue by codeon-nat** [skvadrik/re2c#264]
I tried `07_cxx98.i.c` and `11_http_rfc7230.i--tags.c` but both do not compile, because generator warnings are appended at the end.

e.g.
```
}
11_http_rfc7230.i--tags.re:243:17: warning: tag 'm1' has 2nd degree of nondeterminism [-Wnondeterministic-tags]
11_http_rfc7230.i--tags.re:243:17: warning: tag 'at' has 2nd degree of nondeterminism [-Wnondeterministic-tags]
11_http_rfc7230.i--tags.re:243:17: warning: tag 'u3' has 3rd degree of nondeterminism [-Wnondeterministic-tags]
...
```
And `07_cxx98.i.c` isn't really a C file, as it contains C++ code.

**Comment by skvadrik** [comment]
Please provide complete exact steps of what you are trying to achieve, otherwise I have to guess.

It seems that you are trying to compile autogenerated test results from the `examples` subdirectory. These `.c` files are intended as a reference output for testing purposes: the file contents and the naming scheme follow the convention adopted in re2c testing script (similar to the `test` subdirectory). 

In hindsight I understand that this is confusing. Detailed instructions on how to build and run examples can be found on the website: http://re2c.org/manual/manual.html#more-examples.

**Comment by codeon-nat** [comment]
Your hindsight is correct :) If they are just ephemeral output, why are they part of the project ? Since they aren't compilable C the ending shouldn't be `.c` but `.log` or something.

**Comment by skvadrik** [comment]
@codeon-nat Not ephemeral output --- they are the reference test results (similar to those in the `test` subdirectory). At some point I thought that it's a good idea to add `examples` subdirectory to the list of testing subdirectories. It never occurred to me that the output test results may be confusing.

I can simply copy of examples into tests, but this way examples and tests will soon be out of sync, as someone might add a new example and forget to copy it. I can also symlink examples into tests, but I'm not sure if would not break in some environments. I can add a script that would update the copied examples before running tests (this is probably the best way I can think of so far).

**Comment by codeon-nat** [comment]
I just wanted to let you know that it's confusing for someone checking out the project. With a very cursory I would have thought, "doesn't work, lets try the next github project". I don't see what you gain by putting the output into **git**, but its not my project. In the end it's not a biggie to me.

**Comment by skvadrik** [comment]
> I just wanted to let you know that it's confusing for someone checking out the project.

That's understood, thanks for pointing out!

> I don't see what you gain by putting the output into git.

These files are the test results. Anyone who clones the project should be able to run tests and make sure the output coincides with the reference output.
