### ISSUE TITLE
New debug macro DDUMP_DFA_TREE missing in non-debug case

### ISSUE THREAD

**Issue by HBBroeker** [skvadrik/re2c#266]
As of commit 4061c451c, a build without RE2C_DEBUG set fails, because DDUMP_DFA_TREE  is only defined for the debug-enabled case.  The dummy non-debug version is missing.

**Comment by skvadrik** [comment]
Thanks for the bug report! Here is a fix: https://github.com/skvadrik/re2c/commit/bf1c67f9d774d5f632d33548f90504f2716594d2.

I added non-debug build flavor to the Travis build matrix, so it should catch such errors in the future.
