### ISSUE TITLE
How to reuse a complicated token tail?

### ISSUE THREAD

**Issue by terpstra** [skvadrik/re2c#273]
I was playing around with reducing the size of re2c's lexer and I realized that I have a pattern where there is a potential for a lot of codegen savings.

In pseudo-code:
```
token = op1 | op2 | op3 | ... | id1 | id2 | ...;
...
op1 = op_mod* op1_kind op_body*;
op2 = op_mod* op2_kind op_body*;
op3 = op_mod* op3_kind op_body*;
op_body = op1_kind | op2_kind | op3_kind | op_mod;
...
id1 = id_mod* id1_kind id_body;
id2 = id_mod* id2_kind id_body;
...
id_body = id1_kind | id2_kind | id_mod;
```

Because the lexer needs to remember whether or not it has an op1/2/3/etc, it has to duplicate the op_body* part of the FSM for each operator. If op_body and/or id_body are complicated (ie: Unicode expressions), this becomes the dominant factor in lexer size.

In practice, what I currently do is define: 'op = op_mod* op_body+;' and then further classify the token into op1/op2/op3 after re2c has matched it... using a secondary re2c lexer of course.

I was wondering if there might be some clever way to do this all in one lexer. We have extractors which could at least rip out the opX_kind, so I don't need to re-parse the op_mod* part of the token.  However, I know that re2c underneath uses an edge-tagged DFA. So it should be possible to somehow remember the alternative you took on your way to the op_body part.

I could imagine something like:
```
op3 = op_mod* (op1_kind | op2_kind | op3_kind) op_body* { return ALTERNATIVE_TAKEN; }
```

Is there already a sneaky way to achieve this? If not, is it useful? If not, is the best approach what I already do (capture the location of the alternative and then reclassify after match)?

**Comment by skvadrik** [comment]
Your intuition is quite right, it is possible to avoid duplication by using tags to record which of the alternatives matched. Consider a simplified example: a rule `[a] ([x] | [y] | [z]) [^\x00]*` that matches strings like `axa`, `aya`, `aza`, and suppose we'd like to know which of the alternatives `x`, `y` and `z` matches. Using three different rules causes code duplication for the common tail `[^\x00]*`:
```cpp
#include <stdio.h>

#define YYCTYPE char

int f(const char *s)
{
    const char *YYCURSOR = s;
    /*!re2c
    re2c:yyfill:enable = 0;

    [a] [x] [^\x00]* { return 1; }
    [a] [y] [^\x00]* { return 2; }
    [a] [z] [^\x00]* { return 3; }
    *                { return -1; }

    */
}

int main(int argc, char **argv)
{
    for (int i = 1; i < argc; ++i) {
        printf("%d\n", f(argv[i]));
    }
    return 0;
}
```
However, using tags allows to avoid duplication and have one rule:
```cpp
#include <stdio.h>

#define YYCTYPE char

int f(const char *s)
{
    const char *YYCURSOR = s, *x, *y, *z;
    /*!stags:re2c format="const char *@@;"; */
    /*!re2c
    re2c:yyfill:enable = 0;
    re2c:flags:tags = 1;

    [a] (@x [x] | @y [y] | @z [z]) [^\x00]* {
        if (x)      return 1;
        else if (y) return 2;
        else        return 3;
    }
    * { return -1; }

    */
}

int main(int argc, char **argv)
{
    for (int i = 1; i < argc; ++i) {
        printf("%d\n", f(argv[i]));
    }
    return 0;
}
```
Tags are set to `NULL` on paths that do not match the corresponding alternative, therefore by testing if the tag is `NULL` or not it is possible to tell which alternative has been chosen. (On the matching paths, tags are set to the offset that matches tag position.)

**Comment by terpstra** [comment]
This is great! Thank you so much for this tip.
