### ISSUE TITLE
How can I recursively lex?

### ISSUE THREAD

**Issue by NickStrupat** [skvadrik/re2c#274]
I'm testing the use of re2c on unicode identifiers. Let's say I want my identifiers to allow unicode categories `L | Nl`. That's easy enough if i have the definitions. What I'm stuck on is if I want to allow unicode literals as well. Conceptually, my named definition would be

```
identifier = L | Nl | ("\\u" <Hex literal matching L values>) | ("\\u" <Hex literal matching Nl values>);
```

Assuming that definition can't be specified, I can make a definition to match unicode literals

```
hexLiteral = "\\x" [0-9a-fA-F]+;
unicodeLiteral = "\\u" hexLiteral+;
```

My idea is that when I match a unicode literal, I call the lexer on that value (recursively). But then I don't know how to feed that back into the executing lexer, sort of overriding it?

Any help or guidance would be greatly appreciated. Thanks!

**Comment by skvadrik** [comment]
All you need to relex is to set `YYCURSOR` back to the beginning of the token that you have lexed and transition to the new lexer. It is common to first  run a simple lexer that ensures syntactic validity of the token and finds its end, and than parse the token with a more thorough lexer. For example, here is a `lex` function that first validates the identifier as a sequence of Latin lowercase letters or hexadecimal escapes, and parses it and reconstructs the original string:
```cpp
#include <assert.h>
#include <string>

#define YYCTYPE char

/*!re2c
static std::string lex(const YYCTYPE *YYCURSOR)
{
    const char *YYMARKER, *token;
    std::string str;

    token = YYCURSOR;
    /*!re2c
        *                    { return str; }
        (char | hex)+ [\x00] { YYCURSOR = token; goto parse; }
    */

parse:
    token = YYCURSOR;
    /*!re2c
        *      { return str; }
        char   { str += token[0]; goto parse; }
        hex    { str += (char)unescape_hex(token + 2, YYCURSOR); goto parse; }
        "\\t"  { str += '\t'; goto parse; }
        "\\\\" { str += '\\'; goto parse; }
    */
}

int main()
{
    assert(lex("") == "");
    assert(lex("?") == "");
    assert(lex("xyz") == "xyz");
    assert(lex("x\\x20y") == "x y");
    assert(lex("x\\xffy") == "x\xffy");
    return 0;
}
    re2c:yyfill:enable = 0;
    char = [a-z];
    hex  = "\\x" [0-9a-f]{2};
*/

static unsigned unescape_hex(const YYCTYPE *YYCURSOR, const YYCTYPE *e)
{
    unsigned u = 0;
    for (; YYCURSOR < e;) {
    /*!re2c
        *     { assert(false); }
        [0-9] { u = u * 16 + (YYCURSOR[-1] - 0x30u);      continue; }
        [a-f] { u = u * 16 + (YYCURSOR[-1] - 0x61u + 10); continue; }
    */
    }
    return u;
}

static std::string lex(const YYCTYPE *YYCURSOR)
{
    const char *YYMARKER, *token;
    std::string str;

    token = YYCURSOR;
    /*!re2c
        *                             { return str; }
        (char | hex | "\\t" )+ [\x00] { YYCURSOR = token; goto parse; }
    */

parse:
    token = YYCURSOR;
    /*!re2c
        *      { return str; }
        char   { str += token[0]; goto parse; }
        hex    { str += (char)unescape_hex(token + 2, YYCURSOR); goto parse; }
        "\\t"  { str += '\t'; goto parse; }
        "\\\\" { str += '\\'; goto parse; }
    */
}

int main()
{
    assert(lex("") == "");
    assert(lex("?") == "");
    assert(lex("xyz") == "xyz");
    assert(lex("x\\x20y") == "x y");
    assert(lex("x\\xffy") == "x\xffy");
    assert(lex("x\\ty") == "x\ty");
    return 0;
}
```

**Comment by NickStrupat** [comment]
Thank you! I realized I was over-complicating it.

I will have one lexer that just knows how to convert escape sequences to their code point value, and then the second lexer will only see code point values.

**Comment by skvadrik** [comment]
Good, and I realized that I copy-pasted the code example incorrectly (so I edited the above comment).

**Comment by NickStrupat** [comment]
Thanks I wondered about that. So I've come up with a clean pattern of layered iterators, but i'm still curious... is there a way to tell the lexer it has matched a different definition than it actually has?

Say I have

```
lowercase = [a-z];
uppercase = [A-Z];

lowercase  { return 0; }
uppercase  { <trick the lexer into thinking it matched lowercase> }
* { return 1;
```

Is that supported/possible?

**Comment by skvadrik** [comment]
It depends on what you mean by "tell the lexer it has matched a different definition than it actually has", in your example it could be some post-processing like this:
```
  lowercase { return YYCURSOR[-1]; }
  uppercase { return tolower(YYCURSOR[-1]); }
```
But I think you mean something different, and I'm not sure what.

Generally the two sources of information you have upon matching a rule are: 1) what rule has matched (the control flow transfers to its semantic action), and 2) various pointers to the text that has matched (`YYCURSOR`, often some pointer to the start of the matched text, tags or capturing parentheses that match various points in the middle of the text). You can then either do some post-processing in the semantic action, or adjust the cursor and transfer control flow to another lexer. 

If the input requires a lot of preprocessing (for example, decoding escape sequences or evaluating some macros and substituting them with new input), it may be cleaner to run a pre-lexer in a separate pass.

(Sorry if it's all obvious.)
