### ISSUE TITLE
regexp combining of submatches/TDFA

### ISSUE THREAD

**Issue by shawnl** [skvadrik/re2c#288]
re2c combines regular expressions into a single DFA, however it does not support a tree of regular expressions to generate a TDFA. This allows writing much more understandable regular expressions that still can parse arbitrary regular languages: i.e. instead of this (which relies on C, and if you don't add a default match, you get nasty fall-through behavior):
```
    /*!re2c                          // start of re2c block
    re2c:yyfill:enable  = 0;         //   configuration that turns off YYFILL
    re2c:flags:utf-8 = 1;

    digit  = [0-9];                  //   named definition of 'digit'
    number = digit+;                 //   named definition of 'number'

    [^.] { goto valid_utf8; }
    *    { printf("invalid utf8"); return -1;}
    */
valid_utf8:
    /*!re2c
    * {return -1;}
    number {                         //   a normal rule with its semantic action
        printf("number\n");          //     ... semantic action (continued)
        return 0;                    //     ... semantic action (continued)
    }                                //   end of semantic action
    */                               // end of re2c block
```

you could match like this:

```
   valid_utf8 = [^.]*
   * { printf("invalid utf8\n"); return -1;}
   number <- valid_utf8 { printf("number\n"); return 0;}
```

**Comment by shawnl** [comment]
The point I am trying to make is that regular expression generate a DFA, which is a dag, and that you can also structure your matches as a DAG, and the submatches would use tags of the TDFA, and be optional. Inside the code block you would always see the innermost tag (only). You could also then parse non-regular recursive, context-insensitive languages by adding a simple level count, and context-sensitive but non-turing complete languages by adding a stack.

Yeah, I realize I am not being clear enough that any of this is implementable, but what you have with re2c is really nice, but not complete....especially the TDFA is a super awesome algorithm, and if you make all the tag updates relative to a stack, and reference the tags relative to the inner-most match, this algorithm can be used to parse arbitrary non-turing-complete languages in O(n) time.

**Comment by shawnl** [comment]
All non-Turing complete languages can be represented by using a DAG of regular expressions. The syntax I described above:
```
   valid_utf8 = [^.]*
   * { printf("invalid utf8\n"); return -1;}
   number <- valid_utf8 { printf("number\n"); return 0;}
```

Requires a stack of tags, but for non-context sensitive but recursive (and non-regular) nodes can also point to themselves (but never backwards). (I guess it then is not a DAG, but rather a directed non-context-sensitive graph.) 
```

```

**Comment by skvadrik** [comment]
Hi Shawn,

These are interesting thoughts, but I don't fully understand your idea. In particular, what I don't understand is:

- What is the meaning of your suggested example `number <- valid_utf8` ? Does it mean "match `valid_utf8` and then match `number`"? But that doesn't make sense since you defined `valid_utf8` as a greedy regexp that consumes any number of valid UTF-8 symbols. Also, to match a sequence of two regular expressions you can simply concatenate them.
- Do you have a complete minimal example that you would like to improve? It's hard to discuss small pieces of code that are not syntactically valid.
- What is the class of formal grammars that would be handled by your algorithm? Where would you place it in the Chomsky hierarchy? One of my favorite books on parsing algorithms is "Parsing Techniques. A Practical Guide" by Dick Grune and Ceriel Jacobs [PDF](https://dickgrune.com/Books/PTAPG_1st_Edition/BookBody.pdf). Perhaps you are also familiar with it and can place your algorithm among those described in the book?

Perhaps not what you want, but have a look at start conditions ([description](http://re2c.org/manual/manual.html#start-conditions) and [example](http://re2c.org/examples/example_05.html), contrast it with the same example that [uses blocks](http://re2c.org/examples/example_04.html)). Conditions allow to automate some of the overhead on switching between different blocks.

> All non-Turing complete languages can be represented by using a DAG of regular expressions.

What is a non-Turing complete language? And anyway, I think that a DAG of regular expressions is nothing more than a regular expression, because you can compose the DAG using alternative and concatenation.

> regular expression generate a DFA, which is a dag

DFA is not necessarily a DAG, it often contain cycles, otherwise it won't be possible to generate infinite languages from a finite grammar. For example DFA for `a*` must contain a cycle.

> `[^.]`

Note that this construct means "any valid symbol except literal dot". You probably meant just `[^]`, which is "any valid symbol". Outside of the character class dot has a different meaning: "any valid symbol except newline".

**Comment by shawnl** [comment]
>  I think that a DAG of regular expressions is nothing more than a regular expression, because you can compose the DAG using alternative and concatenation.

OK. The DAG is not of the incoming stream of data, but of the interrelatedness of the matches. Optional submatches if you will.

So the complexity of a regular expression is defined by the alphabet size, and the number of states, however you have no context. For now I am only considering so-called context-free languages (level 2 of Chomsky's Heirarchy). The way of representing complexity of context is

**Comment by shawnl** [comment]
Yeah, I don't have it yet. There is a way to simplify that stack that always shows up when you are parsing a "context-free language" (I'll leave out 3rd level languages for now).

The DAG is not of the states/input alphabet, but of matching---submatches are not mandatory, and they also run in parallel with their parents---the point is to reduce the amount of context that the regular expression requires (while you can do a set number of levels of recursion in regular expressions, it is very expensive---and RE2 admits that it converts " x{2,5} into a sequence of basic operations like xx(x(x(x)?)?)?. "[1]) each level of the submatch DAG has a set amount of context that it needs when it is running on the input (you always only process the input stream once), which is set when compiled and then never changes.

The problem is that a stack always appears--even if you try to just store back-references to fill in later---or even if you use reverse polish notation and have no stack---whatever reads your output then needs a stack. I think the reverse polish notation is the key here, as you can actually parse a context-free (and not regular language) with a set amount of memory---and even validate that the {}s and ()s match. (requires adding counters--and with a 64-bit counter you can process more data than the size of the universe). You just can't traverse it without reading it again in order to "symbolize" it (or can merge this step with the parse to create an impure parser).


[1] https://swtch.com/~rsc/regexp/regexp3.html

**Comment by shawnl** [comment]
I am talking as if regular expression do more than match. I haven't used sed much (mainly because I ran into the lack of non-greedy matches limitation), but as long as it doesn't have limitations in terms of regular languages, and there also is a difference between a Moore machine and a Mealy machine, then that is what I am talking about.

**Comment by shawnl** [comment]
The amazing thing is that you end up with a non-turing-complete langauge (although it is full of channels, all of the same bit width, and as it is basically 3D doesn't look too great as text) that can represent arbitrary machines, including machines that implement turing complete langauges (with the caveat that the amount of state is always limited, so the *infinite* time and space prerequisites of the turing equivilence postulate do not apply).

What remains to be seen is if there is only one and only one representation of a given machine (and what algorithms reduce it to do---we see similar postulates of Moore reduction in NFAs), and if optimization is a NP complete problem or if it is tractable. (My optimistic guess is that there is only one representation and that optimization is tractable---the reason turing machines are more practical is that they are more adaptable particularly in that they can reuse the same non-specialized memory, and that because communication is always regular there are hard trust problems with communicating languages that require context---but this is nothing more than a hunch at this point).

**Comment by shawnl** [comment]
My plan to work on this is to first implement regular expression compiler for FPGAs, and then try to expand it into a sed compiler for FPGAs.

**Comment by skvadrik** [comment]
> What remains to be seen

I still don't see a description of your algorithm, and exactly what problem it solves.

> The amazing thing is that you end up with a non-turing-complete langauge [...] that can represent arbitrary machines, including machines that implement turing complete langauges (with the caveat that the amount of state is always limited, so the infinite time and space prerequisites of the turing equivilence postulate do not apply).

Parsing unrestricted grammar is an undecidable problem. Your algorithm may be able to parse a wider class than regular languages, but it cannot parse all languages (you use the words "arbitrary Turing-complete languages", but that sounds like "all languages recognizable by a Turing machine" to me, which means simply "all languages" under [Church-Turing hypothesis](https://en.wikipedia.org/wiki/Church%E2%80%93Turing_thesis)). It is necessary to understand what class of languages can be parsed by your algorithm. 

> My plan to work on this is to first implement regular expression compiler for FPGAs

There is an interesting discussion why NFAs are better suited for FPGA here: https://github.com/skvadrik/re2c/issues/294.

**Comment by shawnl** [comment]
> Your algorithm may be able to parse a wider class than regular languages, but it cannot parse all languages (you use the words "arbitrary Turing-complete languages", but that sounds like "all languages recognizable by a Turing machine" to me, which means simply "all languages" under Church-Turing hypothesis). 

This is all true. My algorithm takes place in hypothetical space, so while it can parse all languages representable by Turing machines, it cannot represent all languages that can be recognized by turning machines. The difference is the context. While in the abstract my model can represent infinite context, the amount of context is always limited. (This is actually why God is immortal.) You lose the repurpisability of a Turing machine and have much more startup costs, but your can make the implementation of the parser *perfect*.

The problem I am struggling with now is how to do the merges. As Linus Torvalds says "forks are worthless if you can't merge". While I see a number of ways to do it, I am not sure which is best, as there are some tricky race conditions. (In San Francisco I talked to someone about trying to demonstrate a race condition with a water pipe model.)

Because you have to read from two sources, which regular expressions and sed are not made to handle. Do you stuff them together and increase the bit width, or do you block and have select and merge commands in the regular expression? It all starts looking quite messy.

**Comment by shawnl** [comment]
Ok. So i was only thinking of Moore machines, but mealy machines can be represented by an extended form of SSA that adds streams. Every use of the stream value reads from the stream.

I was excited about the `circt` project, and then when they ran into this problem they started doing hacks that will never work, and thinking that they had to abandon SSA form.....

**Comment by shawnl** [comment]
With streams `return` suspends execution. Startup code is before the first reading of a stream, and the amount of state a function needs is fixed, and execution is finished simply by removing this state at a suspension point.

Like with go channels, there is no explicit synchronization. All synchronization is done through communication. That is a mealy machine, which is significantly more complicated than Moore machines, which are simply regular expressions. By using both is a DAG it is possible to parse all non-turing-complete languages, given that the abstract infinite nesting is reduced to a certain quantity of state (perhaps by limiting input length, but also perhaps by limiting the *complexity* of an infinite-length input---so perhaps this will also give a better understanding of Shannon's entropy)

**Comment by shawnl** [comment]
Although Mealy machines can read from multiple streams, and no-one has written regular expressions that do that, yet.

**Comment by skvadrik** [comment]
Thanks for the https://github.com/llvm/circt reference, it's interesting.

Do you have in mind an application for a regular expression that reads from multiple streams?
