### ISSUE TITLE
use switch range

### ISSUE THREAD

**Issue by algorithm314** [skvadrik/re2c#290]
Hello,

is there a way for re2c to produce switch cases that use ranges? 

example:

```c
switch(c){
case 'a'...'z':
}
```
It is not standard C, but it is at least supported by gcc,clang,tcc.

**Comment by skvadrik** [comment]
There is no such option now, but it should be easy to add one. I have a few questions:
- Why do you want it?
- What are the corresponding options in GCC/Clang/Tcc?
- Can you provide link to a part of C/C++ standard that describes this language feature?

**Comment by skvadrik** [comment]
To clarify why I'm asking these questions: if this feature is enabled with some compiler option, we'd probably like to name it similarly in re2c. As for the standard, I just need a more-or-less formal description of the extension syntax (to avoid adding partial or incorrect support). Otherwise it's clear from your example.

**Comment by algorithm314** [comment]
Hello,
Thank you for the response.

I don't want it for something special. I have a tokenizer and looking in the generated code most of the cases happen to be consecutive.

Advantages that i can think of are more readable and smaller generated code.(Though not many look into generated code).

It is described [here](https://gcc.gnu.org/onlinedocs/gcc/Case-Ranges.html)

No extra options are need to the compiler.

**Comment by skvadrik** [comment]
Thanks for the link! I have added option `--case-ranges` and configuration `re2c:flags:case-ranges` in commit https://github.com/skvadrik/re2c/commit/cb11abb3d4ddb65e6ee884f1eb3aa3c3c734093e.

**Comment by algorithm314** [comment]
Thank you skvadrik,

I made a test for my tokenizer.

* old code size is 61.1K lines, reduced to 17.5K
* generated binary size and speed for gcc,clang is the same
* for tcc size binary size is reduced 3x with 1.6x improvement in throughput

**Comment by skvadrik** [comment]
Awesome! Who would expect that this would make so much difference for Tcc.

**Comment by skvadrik** [comment]
Thanks, this is useful information. I now remember that I saw Tcc produce much smaller binaries, and much faster running times with `-b` option (in an unrelated experiment: https://arxiv.org/pdf/1907.08837.pdf, pages 27-28). Your measurements confirm those results and shed more light on how Tcc works.
