### ISSUE TITLE
Conditions required for all lexers when using '-c' option

### ISSUE THREAD

**Issue by jinscoe123** [skvadrik/re2c#296]
#### Example

```c
#include <assert.h>
#include <string.h>


/*!types:re2c */

int lex_char(const char* cur, const char* lim)
{
    int condition = yycinit;
    const char* mrk;

    char yych;

    /*!re2c
        re2c:define:YYCTYPE = char;
        re2c:define:YYLIMIT  = lim;
        re2c:define:YYCURSOR = cur;
        re2c:define:YYMARKER = mrk;
        re2c:yych:emit = 0;
        re2c:yyfill:enable = 0;

        "\\"                { return -1; }

        "\\f"               { yych = '\f'; goto done; }
        "\\n"               { yych = '\n'; goto done; }
        "\\r"               { yych = '\r'; goto done; }
        "\\t"               { yych = '\t'; goto done; }
        "\\v"               { yych = '\v'; goto done; }

        *                   { goto done; }
    */

done:
    return cur == lim ? yych : -1;
}

int lex(const char* cur)
{
    const char* lim;
    const char* mrk;

    char yych;

    int condition = yycinit;

    lim = cur + strlen(cur);
loop:
    mrk = cur;

    /*!re2c
        re2c:define:YYCTYPE = char;
        re2c:define:YYLIMIT  = lim;
        re2c:define:YYCURSOR = cur;
        re2c:define:YYMARKER = mrk;
        re2c:yych:emit = 0;
        re2c:define:YYGETCONDITION = 'condition';
        re2c:define:YYGETCONDITION:naked = 1;
        re2c:define:YYSETCONDITION = 'condition = @@;';
        re2c:define:YYSETCONDITION:naked = 1;
        re2c:yyfill:enable = 0;
        re2c:eof = 0;

        <init> *                                        { return -1; }
        <init> $                                        { return  0; }

        <init> [/][/] .*                                { goto loop; }
        <init> [/][*]                   => comment      { goto loop; }

        <init> [ \t]+                                   { goto loop; }

        <init, comment> [\n]+                           { goto loop; }

        <comment> [^*\n]+ [*]*          => comment      { goto loop; }
        <comment> [^*\n]* [*]+          => comment      { goto loop; }
        <comment> [^*\n]* [*]+ [/]      => init         { goto loop; }

        <comment> *                     => comment      { goto loop; }
        <comment> $                                     { return -1; }

        <init> ['] ([\\][^\n] | [^'\n])+ [']            {
            int chr = lex_char(mrk + 1, cur - 1);
            if (chr < 0) {
                return -1;
            } else {
                goto loop;
            }
            }
    */
}


int main(void)
{
    assert(!lex("/* hello, */ '\\n' // world !"));

    return 0;
}
```

#### Compile

```
re2c -W -Werror -c -o bug.c bug.re && gcc -o bug bug.c
```

#### Error

```
bug.re:22:28: error: non-conditional rules are not allowed with '-c', '--conditions' option
```

#### Description

As you can see, the main lexer in `lex()` uses start conditions, but the sub-lexer in `lex_char()` has no need for them. Re2c, however, complains when the sub-lexer does not use start conditions. This may or may not be expected behavior, but I didn't see anything in the documentation about it, so I created this issue. Either way, it seems to me that it would be more convenient to allow one to intermix blocks with and without start conditions within the same file.

**Comment by skvadrik** [comment]
This _is_ expected behavior, but I also find it inconvenient. Features like conditions and reuse mode go back to the early days, where most of the re2c users had one giant lexer per file (typically a tokenizer for some programming language). I already changed reuse mode to allow mixing normal blocks and rules/use blocks, and I'm all for allowing to mix condition blocks with normal blocks. But this requires a bit of thinking to catch all possible corner cases.

**Comment by jinscoe123** [comment]
Okay, no problem. It isn't a big deal to have to add `<init>` before each rule. Now that #295 is fixed, this is just a slight inconvenience.

**Comment by skvadrik** [comment]
Commit https://github.com/skvadrik/re2c/commit/2a9c122e67d5c52afe7aec33921f76a9cc70b0ad allows mixing conditional and normal blocks in `-c` mode.

**Comment by jinscoe123** [comment]
Thank you! As always, you work is much appreciated. :)

**Comment by neil-edelman** [comment]
Now, is there any reason not to have `--conditions`? Doesn't that make it redundant? (So a Makefile with `.re_c.c` and `.re.c` could be collapsed.)

**Comment by skvadrik** [comment]
> Now, is there any reason not to have `--conditions`? Doesn't that make `--conditions` redundant?

You mean, enabling conditions by default? I suppose that can be done (similar to `-r` flag that was unconditionally enabled in version 2.2).

**Comment by skvadrik** [comment]
The change itself is trivial, but what also needs to be fixed is documentation (and it is a bit more work).

**Comment by neil-edelman** [comment]
I've never used `re2c` in any other languages, but I think in C, at least, now tags and conditions are a superset of functionality. Such that one default make rule `%.c: %.re.c, re2c -W -T -c -o $@ %<`.
