### ISSUE TITLE
configure error on ubuntu 18.04 / cmake 3.10

### ISSUE THREAD

**Issue by sekiguchi-nagisa** [skvadrik/re2c#297]
The following error is generated when trying to configure
```
CMake Error at CMakeLists.txt:2 (project):
  project with VERSION must use LANGUAGES before language names.


-- Configuring incomplete, errors occurred!
```

Reproduction steps
```sh
git clone https://github.com/skvadrik/re2c.git
cd re2c
cmake .
```

cmake version
```
$ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

``CMakeLists.txt`` uses newly added (introduced from cmake 3.12) features such as  ``HOMEPAGE_URL`` parameter in ``project() `` command, ``add_compile_definitions()`` command.
see [CMake 3.12 Release Notes](https://cmake.org/cmake/help/v3.12/release/3.12.html).

I think the simplest solution is changing ``cmake_minimum_required`` with 3.12 or later

**Comment by skvadrik** [comment]
Thanks, I have raised the minimum required version to 3.12 in https://github.com/skvadrik/re2c/commit/f025279f98bcd50941dc6b56783ee9afaf93da20. Let me know if you need support for earlier versions of CMake, I think things like `HOMEPAGE_URL` or `add_compile_definitions()` can be rewritten or removed.

**Comment by sekiguchi-nagisa** [comment]
Thank you :+1:
