### ISSUE TITLE
re2c produces invalid code when format string for stag is other than '@@'

### ISSUE THREAD

**Issue by sakovetsa** [skvadrik/re2c#299]
Consider the following C program (note that format string for stag is not '@@').
```C
#include <assert.h>

int lex(char *p, unsigned int len)
{
    char *YYCURSOR = p, *YYLIMIT = p + len, *YYMARKER;
    char *s1, *s2;

    /*!stags:re2c format = 'char *re2c_stag_@@;'; */

    /*!re2c
    re2c:define:YYCTYPE           = char;
    re2c:yyfill:enable            = 0;
    re2c:flags:tags               = 1;

    @s1 [0-9]+ @s2  { return s2 - s1; }
    *               { return -1; }

    */
}

int main(int argc, char *argv[])
{
    assert(lex("123", 3) == 3);
}
```

Here is the output produced by re2c, irrelevant parts omitted.
```
int lex(char *p, unsigned int len)
{
    char *YYCURSOR = p, *YYLIMIT = p + len, *YYMARKER;
    char *s1, *s2;

    char *re2c_stag_yyt1;

    
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '0' ... '9':
		yyt1 = YYCURSOR;
		goto yy4;
	default: goto yy2;
	}
yy2:
	++YYCURSOR;
	{ return -1; }
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0' ... '9': goto yy4;
	default: goto yy6;
	}
yy6:
	s1 = yyt1;
	s2 = YYCURSOR;
	{ return s2 - s1; }
}

}
```
There are lines ```yyt1 = YYCURSOR;``` and ```s1 = yyt1;```
For some reason re2c refers to variable ```yyt1```, which is undefined. I believe it should be ```re2c_stag_yyt1 = YYCURSOR``` and ```s1 = re2c_stag_yyt1```, or am I missing something?

**Comment by skvadrik** [comment]
Use `re2c:tags:expression = "re2c_stag_@@";` configuration to specify the form of tag expressions in the main body of the lexer (after adding it the test compiles and runs without errors). The reason why it is necessary to specify in two places is because the `/*!stags:re2c*/` directive may be used in other contexts, for example to generate initializer lists or define tags as arguments to functions.

If you only need to change the prefix, is it easier to use `re2c:tags:prefix = "re2c_stag_";` configuration, then there is no need to add the prefix to `@@` formal parmeter:
```c
#include <assert.h>

int lex(char *p, unsigned int len)
{
    char *YYCURSOR = p, *YYLIMIT = p + len, *YYMARKER;
    char *s1, *s2;

    /*!stags:re2c format = 'char *@@;'; */

    /*!re2c
    re2c:define:YYCTYPE  = char;
    re2c:yyfill:enable   = 0;
    re2c:flags:tags      = 1;
    re2c:tags:prefix     = "re2c_stag_";

    @s1 [0-9]+ @s2  { return s2 - s1; }
    *               { return -1; }

    */
}

int main(int argc, char *argv[])
{
    assert(lex("123", 3) == 3);
}
```

**Comment by sakovetsa** [comment]
Got it, thank you. Should have read documentation more carefully ;)

**Comment by skvadrik** [comment]
It's fine to ask!

Forgot to say, it would be impossible for re2c to infer that you want all tags to be prefixed with `re2c_stag_` from the configuration text `'char *re2c_stag_@@;'`. It does not parse the code in configurations, it only performs a simple string substitution. Even if re2c did parse the code, it would be hard for it to know which part of the enclosing expression to use.
