### ISSUE TITLE
cannot compile with gcc-3.3.1 on cygwin

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#3]
Hi,

I'm the Cygwin gcc maintainer and wanted to build and 
distribute re2c for Cygwin.

But I cannot compile the provided scanner.cc, getting 
this error from g++:

g++ -o scanner.o -O2 -Wall -I. -Wno-unused -Wno-
parentheses -Wno-deprecated -c scanner.cc
scanner.re: In member function `int Scanner::echo
(std::ostream&)':
scanner.re:79: error: invalid conversion from `uchar*' to 
`const char*'
scanner.re:79: error:   initializing argument 1 of 
`std::basic_ostream&lt;_CharT, 
_Traits&gt;& std::basic_ostream&lt;_CharT, _Traits&gt;::write
(const _CharT*, int) 
[with _CharT = char, _Traits = std::char_traits&lt;char&gt;]'
scanner.re:75: error: invalid conversion from `uchar*' to 
`const char*'
scanner.re:75: error:   initializing argument 1 of 
`std::basic_ostream&lt;_CharT, 
_Traits&gt;& std::basic_ostream&lt;_CharT, _Traits&gt;::write
(const _CharT*, int) 
[with _CharT = char, _Traits = std::char_traits&lt;char&gt;]'
make: *** [scanner.o] Error 1

Any hints please,

Gerrit

Original comment by: siebenschlaefer

**Comment by linuxlovell** [comment]
thanks www.movied.org
