### ISSUE TITLE
Add rst2c tool instead of gen_help.sh.

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#327]
Currently the way we generate help message is from the .rst sources (shared between the manpage, help message and online documentation) to an intermediate manpage, and from the intermediate manpage to a C++ literal string: doc/help.rst.in -> (configure) help.rst -> (rst2man) help.rst.1 -> (gen_help.sh) help.cc.

It is possible to simplify the process, bypass the intermediate manpage and generate C++ source code from the .rst sources directly, if we write a tool rst2c that will convert help.rst to help.cc. Then we could get rid of the man invocation and make it work on Windows without Cygwin.

**Comment by sergeyklay** [comment]
I'd like to declare some points that we may want to test during some test suite:

- The manpage was created
- The output of `--help` is not empty
- The line width of `--help`  output is 80
- The `--help`  output starts from USAGE word w/o extra lines before
- The `--help`  output "footer" does not contain extra lines
- The content of  the `--help`  output is the same as the relevant manpage part

**Comment by sergeyklay** [comment]
Just to share one of the possible solutions for testing the command output: for blackbox testing (run a command and verify the output/result) I used https://github.com/chriscool/sharness

**Comment by skvadrik** [comment]
This looks neat!

Comparing command output against the reference output will not work if the .rst sources have changed (because the output will change accordingly). This comparison will only succeed when the help is regenerated from the same sources.

Ideally we should also run spell-checker on all .rst files (with a custom dictionary), such as `aspell -c`. I find errors way too often when I run it manually after updating the docs. But that is a different issue and quite a bit of work on top of writing the script.

**Comment by idigdoug** [comment]
I think this can be closed now.

**Comment by skvadrik** [comment]
> I think this can be closed now, unless we want to wait for the autotools build to match.

We do: the two build systems should be on par, as they are both used. Now that you've done the difficult part and wrote the scripts, it's should be easy to fix autotools and get rid of the old gen_help.sh (I can take a look after merging you PRs https://github.com/skvadrik/re2c/pull/421 and https://github.com/skvadrik/re2c/pull/422).

**Comment by idigdoug** [comment]
Sounds good. I can look into it as well. Agree that it shouldn't be hard.

**Comment by skvadrik** [comment]
@idigdoug fixed this in https://github.com/skvadrik/re2c/pull/419 and https://github.com/skvadrik/re2c/pull/426. Closing.
