### ISSUE TITLE
[Request]: Tarball distribution with lzip

### ISSUE THREAD

**Issue by selkfoster** [skvadrik/re2c#342]
Hello!

Thanks for your work on re2c! I wonder if re2c can be distributed using the lzip[1] format.

[1] http://lzip.nongnu.org/

**Comment by skvadrik** [comment]
Sure, it is a one-liner change in `AM_INIT_AUTOMAKE` (one-word even): https://github.com/skvadrik/re2c/commit/c189eb7d9d0967d543475d5986b66d3dd6a06dda

**Comment by selkfoster** [comment]
Hello @skvadrik,

Yes! automake has the support for the lzip target.

I am a free software distributor, so I will be able to distribute re2c in our preferred format.  Thank you!
