### ISSUE TITLE
No CMakelists.txt file in new 2.1 release

### ISSUE THREAD

**Issue by david-geiger** [skvadrik/re2c#346]
Hi,

I tried to compile latest re2c 2.1 release on Mageia Cauldron but in re2c-2.1.tar.xz source tarball the cmake build part is missing.

> CMake Error: The source directory "/home/iurt/rpmbuild/BUILD/re2c-2.1" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
error: Bad exit status from /home/iurt/rpmbuild/tmp/rpm-tmp.7IFMIn (%build)

Regards,
David

**Comment by skvadrik** [comment]
Thanks for reporting! The file was accidentally dropped from EXTRA_DIST in https://github.com/skvadrik/re2c/commit/9959efed383379b4432bdab3812b34bc381a544a. I will release an update a bit later.

**Comment by skvadrik** [comment]
Released 2.1.1 with the fix.

**Comment by david-geiger** [comment]
Thank you so much :)
