### ISSUE TITLE
Scoped directives

### ISSUE THREAD

**Issue by hddharvey** [skvadrik/re2c#369]
re2c is emitting tag variables `yyt1`, `yyt2` and `yyt3` at the location where I wrote
```
/*!stags:re2c format = 'const char* @@ = nullptr;'; */
```
However, `yyt2` and `yyt3` are not used anywhere in the function, causing the compiler to warn about unused variables. It would be nice if this didn't happen so that I don't have to turn off compiler warnings that I like having, or try to do custom warnings for each source file.

I have two lexers in that file, both in separate functions, and re2c also automatically defines tag variables of the same name for that second lexer. However, the second lexer uses all three of those variables, so maybe re2c is not eliminating the unused tag variables in the first lexer because it sees them being used in the second lexer.

It seems to me like the problem here is that the
```
/*!stags:re2c format = 'const char* @@ = nullptr;'; */
```
directive is not connected to particular `/*!re2c ... */` blocks, so re2c can't decide to generate only the tag variables used by a particular re2c block. Instead, it generates all the variables in all `/*!stags:re2c ... */` invocations to be safe.

So you would need a way to associate `/*!stags:re2c ... */` directives with `/*!re2c ... */` blocks. This also means that, if you have multiple structs with `/*!stags:re2c ... */` (like in the documentation examples) and multiple lexers in a file, then there might be some unnecessary injection of variables into structs that don't need them.

## Potential solution

Provide a way to associate `/*!stags:re2c ... */` directives with particular `/*!re2c ... */` blocks. re2c could also make sure that all distinct tag variables were given unique names (in the same file), just to ensure that multiple `/*!stags:re2c ... */` uses for lexers in the same function did not clash. So for the above example, lexer 1 would get `yyt1` and lexer 2 would get `yyt2, yyt3, yyt4`. If they get used in the same function, or are defined as global variables, then there's no clash, and if they're used in separate functions, there's no unused variable warnings.

Maybe you could associate them by giving the re2c blocks a name or something? Maybe that could fit in with the theme of named use blocks discussed in #366 ?

Another random thing I just realized is that the `/*!stags:re2c ... */` directives must be in the same file as the `/*!re2c ... */` blocks, which might be annoying if you want a struct that stores the tag variables to go in a separate header file. However, at the moment you could get around this with preprocessor directives to remove certain parts of the emitted file when used as a header file - might be an issue if the emitted file is gigantic (mine is 140k lines), but that would be a viable solution and it's probably not worth implementing a built-in feature to achieve that.

**Comment by skvadrik** [comment]
> It seems to me like the problem here is that the [...] directive is not connected to particular `/*!re2c ... */` blocks

Yes, that's the root of the problem. Initially re2c was designed without for one-lexer files, and the syntax did not allow scoping. So any directive has to be global and accumulate information across the whole file. It is inconvenient.

> Provide a way to associate `/*!stags:re2c ... */` directives with particular /*!re2c ... */ blocks.

Good point, I'm working on that now. There are many directives in re2c, and they all need to be well-tested in different configurations, so it's not a quick fix). The syntax will be: `/*!stags:re2c:x:y:z ... */` if you want tags to be generated for blocks named `x`, `y` and `z`. It is possible to specify one or more non-duplicate block names, and if the names are omitted then the directive is global and accumulates all blocks (so it works as before).

> Another random thing I just realized is that the /*!stags:re2c ... */ directives must be in the same file as the /*!re2c ... */ blocks [...]

There is a way: generate a header file from your .re file. Here is the relevant part of docs: https://re2c.org/manual/manual_c.html#header-files. This is also used in re2c own lexer: https://github.com/skvadrik/re2c/blob/master/src/parse/lex.re#L64-L121. This feature has been around for a while.

**Comment by skvadrik** [comment]
> re2c could also make sure that all distinct tag variables were given unique names (in the same file)

That is another good point. It would require more work though, currently tag variables have block-local numbering.

**Comment by hddharvey** [comment]
Ah, that header file feature is just what the doctor ordered. No issue there then.

**Comment by skvadrik** [comment]
Support for block lists in `stags:re2c` and `mtags:re2c` has been merged into master in https://github.com/skvadrik/re2c/commit/ca0ebe9c5849b356413cfff33916b8eb016e5b3a.

> re2c could also make sure that all distinct tag variables were given unique names (in the same file)

I thought about this a bit more and realized that if needed, it is fairly easy to achieve by setting block-specific prefix for tag variables (using `re2c:tags:prefix` configuration).

**Comment by hddharvey** [comment]
Thanks, I'll have a look at this when I get the chance.

**Comment by hddharvey** [comment]
@skvadrik Works fine. No longer get the unused tag variables. I didn't need the custom prefixes for my application (since the lexers were in separate functions), but I tested it out anyway and it worked fine. Thanks for implementing this!

**Comment by skvadrik** [comment]
Thanks for confirming @hddharvey !
