### ISSUE TITLE
Default rule != Invalid code-point rule

### ISSUE THREAD

**Issue by terpstra** [skvadrik/re2c#375]
Sometimes, when writing a lexer, I'd like to be able to prove that the default rule is unreachable. For simple ASCII parsers, I can do that with `[*] { #errror ... }`. Unfortunately, with Unicode there is no way to do the same thing, because invalid unicode is caught by `[*]`.

**Comment by skvadrik** [comment]
You can use `[^]` to match any code point. For ASCII, `[^]` is the same as `*`. For Unicode, `[^]` matches any sequence of code units that corresponds to a code point. You should still define `*` in that case to capture code unit sequences that do not correspond to any code point. See [-Wundefined-control-flow](http://re2c.org/manual/warnings/warnings.html#wundefined-control-flow) and [the old defule rule](http://re2c.org/manual/warnings/warnings.html#the-old-default-rule) in particular.

If that's not what you mean, please provide an example.

**Comment by skvadrik** [comment]
Closing. @terpstra Please reopen if `[^]` is not what you need.
