### ISSUE TITLE
Tags incorrectly set with lookahead

### ISSUE THREAD

**Issue by SynAckFin** [skvadrik/re2c#380]
When a tag is added to the lookahead portion of a regexp it is incorrectly set.

As an example, some of the code generated by the following rule:

`    @TS "a" / "bcd" @TE "efgh" { return 0; }`

looks like this (comments are mine):

```
        yych = *++YYCURSOR;
        switch (yych) {
        case 'h':       goto yy12;   // Matched the "h" from "efgh"
        default:        goto yy6;
        }
yy12:
        ++YYCURSOR;        // Step cursor past the "h"
        YYCURSOR -= 7;     // Move cursor to beginning  of lookahead
        TS = YYCURSOR - 1; // Set TS 
        TE = YYCURSOR - 4; // Sets TE to before start of input!! It thinks the cursor is after the "efgh"

```

**Comment by skvadrik** [comment]
Confirmed, thanks for reporting. I will post a patch soon.

**Comment by skvadrik** [comment]
Fixed in: https://github.com/skvadrik/re2c/commit/68e1ab7160a367bf98d215fe90279cee26ec5ee8. @SynAckFin can you confirm that it works for you?

**Comment by SynAckFin** [comment]
Confirmed. Works in both the simple example and the more complex code I'm working on with no side effects detected.

**Comment by skvadrik** [comment]
Thank you! Closing the bug.
