### ISSUE TITLE
Cannot comment in the brace of user code.

### ISSUE THREAD

**Issue by krishna116** [skvadrik/re2c#391]
For example, re2c v2.2 cannot compile follow code because "//comment" used in the brace.
```
int lex(const char *YYCURSOR) 
{
    for(;;)
    {
    /*!re2c
        re2c:define:YYCTYPE = char;
        re2c:yyfill:enable = 0;
        
        [123]   { //printf("%c", *YYCURSOR); break; }
    */
    break;
    }
    return 0;
}
```
The error is:
![image](https://user-images.githubusercontent.com/41564221/146624889-bfe2e3ed-7f37-46ad-b523-96655fe21e3d.png)

**Comment by skvadrik** [comment]
This is because `//` comments everything up to the end of line. This is not re2c-specific behavior, it is simply how single-line comments work in any language.

You can either break the code into multiple lines:
```
    [123] {
        //printf("%c", *YYCURSOR);
        break;
    }
```
Or use a nested multiline comment `/* ... */`:
```
    [123] { /*printf("%c", *YYCURSOR);*/ break; }
```

**Comment by krishna116** [comment]
Ok, thank you for the explain and detail example, so it is closed.
