### ISSUE TITLE
Failed to build master branch on Cygwin/MSYS2 fails

### ISSUE THREAD

**Issue by adlerzei** [skvadrik/re2c#424]
Trying to build the current master branch on my Windows machine fails with the following error message:
```
In file included from src/main.cc:5:
./src/msg/msg.h:28:52: error: ‘va_list’ has not been declared
   28 |     void verror(const loc_t& loc, const char* fmt, va_list args) RE2C_ATTR((format(printf, 3, 0)));
      |                                                    ^~~~~~~
```
When I go back to the last tagged release commit (3.0), the build works correctly. Did you maybe miss some includes after adding the said line?

**Comment by skvadrik** [comment]
@adlerzei Thanks for reporting! I pushed a fix: https://github.com/skvadrik/re2c/commit/f006e755139d8c7b847e8348a9ed5ba63756011b
