### ISSUE TITLE
SEGV

### ISSUE THREAD

**Issue by dtp555-1212** [skvadrik/re2c#433]
re2c 3.0 crashes when trying to process the attached file
[crash.zip](https://github.com/skvadrik/re2c/files/10467779/crash.zip)

**Comment by skvadrik** [comment]
It looks like a stackoverflow to me. A number of those have been fixed recently, and I can reproduce segfault on re2c-3.0 but not on the one built from git. Can you check with the most recent re2c built from git?

**Comment by dtp555-1212** [comment]
Yes... Building from the repo has the same failure

**Comment by skvadrik** [comment]
This is how I tried to reproduce:
```bash
$ git clone https://github.com/skvadrik/re2c
$ cd re2c
$ autoreconf -W all -i
$ build/__build.sh
$ cd __build
$ wget https://github.com/skvadrik/re2c/files/10467779/crash.zip
$ unzip crash.zip
$ ./re2c c.re
```
There is no segfault, output is generated as expected.

**Comment by dtp555-1212** [comment]
Thanks... I will give that a shot!

Thanks again
________________________________
