### ISSUE TITLE
Generated header file is not present in depfile

### ISSUE THREAD

**Issue by madebr** [skvadrik/re2c#440]
When generating a header file, the generated dependency file should contain a rule for the header as well.

How to reproduce:
```bash
cat >o.re <<EOF
/*!include:re2c "i1.re" */
/*!header:re2c:on */
/*!include:re2c "i2.re" */
/*!header:re2c:off */
EOF
touch i1.re i2.re
re2c o.re -o o.c -t o.h --depfile o.deps
```
The content of the depfile, generated by re2c from current master is:
```
o.c: i1.re i2.re o.re
```

I expect it to look as follows instead:
```
o.c o.h: i1.re i2.re o.re
```

**Comment by skvadrik** [comment]
Thanks for reporting and for the reproducer, here's a fix: https://github.com/skvadrik/re2c/commit/f807f7636e1ef9000e267d53ec59f65c13e60dbb.

**Comment by madebr** [comment]
Thanks!
