### ISSUE TITLE
Document -Wnondeterministic-tags

### ISSUE THREAD

**Issue by jvoisin** [skvadrik/re2c#443]
Currently, `-Wnondeterministic-tags` isn't documented on https://re2c.org/manual/warnings/warnings.html

**Comment by skvadrik** [comment]
Here's the updated documentation: https://re2c.org/manual/warnings/warnings.html#wnondeterministic-tags (please reopen if you think it needs further changes). I also noticed that there was no link to the warnings page so I added one on top of the [Warnings](https://re2c.org/manual/manual_c.html#warnings) manual section.
