### ISSUE TITLE
Re2go fail when compiling expression containing combining character

### ISSUE THREAD

**Issue by RadhiFadlillah** [skvadrik/re2c#447]
I'm trying to generate Go code for regular expression `güncellen?me`. I made my re2go input file like this:

```go
package main

import (
	"fmt"
)

func parse(str string) {
	var cur, mar int

	for cur < len(str) {
		/*!re2c

		re2c:tags               = 1;
		re2c:yyfill:enable      = 0;
		re2c:define:YYCTYPE     = byte;
		re2c:define:YYPEEK      = "str[cur]";
		re2c:define:YYSKIP      = "cur += 1";
		re2c:define:YYBACKUP    = "mar = cur";
		re2c:define:YYRESTORE   = "cur = mar";

		güncellen?me {
			fmt.Println("MATCH FOUND")
			return
		}
		[\000] { return }
		*      { continue }
		*/
	}
}

func main() {
	parse("<html><body><p><em>Son güncelleme: 5/5/2020</em></p></body></html>\000")
}
```

Then I run re2go like this:

```
re2go -u --flex-syntax -i main.go -o hmm.go
```

Unfortunately it always fail with following message:

```
input.go:25:5: error: unexpected character: '�'
```

Any tips on how to solve this issue? Thanks!

**Comment by RadhiFadlillah** [comment]
Nevermind. Was stupid, found #237, got smarter.

**Comment by skvadrik** [comment]
@RadhiFadlillah Also not that `for cur < len(str)` is not a correct way of handling the end of input, you can replace it with just `for`. It is the sentinel rule `[\000] { return }` that stops the lexer. More info here: http://re2c.org/manual/manual_go.html#handling-the-end-of-input.

**Comment by skvadrik** [comment]
Here's a fix: https://github.com/skvadrik/re2c/commit/cbd52e0b8eea3687ada56b70292a7af79af1fb5c, it will be merged into master once it passes all the CI checks.

**Comment by skvadrik** [comment]
I'll close this bug, please reopen if you have any further issues.
