### ISSUE TITLE
Suggestion: Zig support

### ISSUE THREAD

**Issue by kassane** [skvadrik/re2c#451]
From 0.10 it is already possible to use the self-hosting compiler (stage2).

**Updated**:  https://ziglang.org/download/0.11.0/release-notes.html

**References:**
- https://github.com/ziglang/zig/issues/630
- https://github.com/ziglang/zig/issues/2162
- https://github.com/ziglang/zig/issues/8220
- https://github.com/ziglang/zig/pull/16306
- https://ziglang.org/documentation/master/std/ziglexer.js

**Comment by skvadrik** [comment]
Zig support was added in experimental branch `syntax-files`: https://github.com/skvadrik/re2c/commit/5cd48a8ffb1bfc82b17bd7f381437efd1678b188. See examples: https://github.com/skvadrik/re2c/tree/syntax-files/examples/zig.

**Comment by kassane** [comment]
@skvadrik , finally thx!
I'll test it.
