### ISSUE TITLE
Document C++11 compiler requirement in BUILD.md

### ISSUE THREAD

**Issue by ryandesign** [skvadrik/re2c#453]
BUILD.md says:

https://github.com/skvadrik/re2c/blob/ece4bb76e39db7071d5dd374d166008d5f982c3f/BUILD.md?plain=1#L8

But in fact one appears to need a C++11-compatible compiler; please document this.

**Comment by skvadrik** [comment]
Thanks! Fixed in https://github.com/skvadrik/re2c/commit/7d6641778cd10fcdc9b5d32f7319ece7aadc95c0.
