### ISSUE TITLE
BUILD.md not present in tarball

### ISSUE THREAD

**Issue by ryandesign** [skvadrik/re2c#454]
README.md says:

https://github.com/skvadrik/re2c/blob/ece4bb76e39db7071d5dd374d166008d5f982c3f/README.md?plain=1#L50-L51

but there is no file BUILD.md in the 3.1 tarball. It's in the repository, so presumably you just need to tell whatever part of the build system creates the tarball to include that file.

**Comment by skvadrik** [comment]
Thanks! Fixed in https://github.com/skvadrik/re2c/commit/3841e83f8511123bf9fac0b1f6dedd24ce6c7de7.
