### ISSUE TITLE
How to get the m4 folder and files within?

### ISSUE THREAD

**Issue by michacassola** [skvadrik/re2c#475]
Hey, I am trying to build re2c with Autotools with GitHub Actions:
Build repo: https://github.com/unypkg/re2c
Latest run: https://github.com/unypkg/re2c/actions/runs/8741186605/job/23986620028#step:2:1
(Tried to copy what I found here: https://github.com/skvadrik/re2c/blob/3.1/.github/workflows/ci-autotools.yml)

I get the error when running autogen.sh:
`aclocal: warning: couldn't open directory 'm4': No such file or directory`

But I noticed your m4 folder is missing in the repo. How do I generate it?
I see that debian's repo has it: https://salsa.debian.org/jcfp/re2c/-/tree/master?ref_type=heads

Thank you very much in advance! 😀

**Comment by skvadrik** [comment]
Hi!

I think you can ignore the warning by aclocal (I have it too in my local repo), `autoreconf -W all -i` creates the /m4 directory anyway.

See https://re2c.org/build/build.html for build instructions.

I'm not sure about the Debian repo; @jcfp may know better why it has the /m4 directory.

**Comment by michacassola** [comment]
Thanks, I can confirm that the m4 folder is generated, so the warning can be ignored. Thanks @skvadrik ! 😀

It seems the problem is a different one:
https://github.com/skvadrik/re2c/issues/476
