### ISSUE TITLE
Are the re2c release tar balls signed?

### ISSUE THREAD

**Issue by rmccullagh** [skvadrik/re2c#488]
I am wondering if there is a way to verify the GitHub release tar balls.

**Comment by skvadrik** [comment]
No, they are not signed.

> I am wondering if there is a way to verify the GitHub release tar balls.

Well, there is a way -- the build should be reproducible, so you can clone re2c repo, `git --reset` to the desired release tag and run `make distcheck`. This will build the tarballs, and then you can compare the hashes with those downloaded from github. It's probably too much effort unless you are a distro maintainer. ;)

**Comment by skvadrik** [comment]
> If the tarballs you use are the ones generated by github and you download them over https:, you're trusting github, but no more than you're trusting them with the storage of the version controlled code in the first place.

Hmm, I think it's easier to change one binary artifact and go unnoticed than it is to change the source code (which is cloned by many people) and still go unnoticed. So I see why signing the binary artifacts may be useful (and hopefully not hard to do). It just never crossed my mind, and this is the first time someone asked.

**Comment by trofi** [comment]
> I am wondering if there is a way to verify the GitHub release tar balls.

Probably not. My suggestion would be to build a tarball yourself and check against the upstream-provided tarball with a tool like [`diffoscope`](https://diffoscope.org/). That way you can find quicker what exactly diverges in your environment and environment used to generate upstream tarballs (`autoconf` delta, `re2c` build version, `bison` version, etc.).

What would you like to verify? The identity of a person generating the tarball? Or the correspondence of git tree tag to a release tarball? If it's the second you might consider using direct git checkouts or snapshots, but note that `re2c` git tags are also not signed so far.

**Comment by pmetzger** [comment]
Signing the tags is the only thing that would make sense, tbh, but barely anyone bothers these days.
