### ISSUE TITLE
Support new Zig's labeled switch/continue

### ISSUE THREAD

**Issue by Ev1lT3rm1nal** [skvadrik/re2c#492]
So, issue https://github.com/ziglang/zig/pull/21257 was closed, adding support for new syntax for labeled `switch/continue` statements, which improves performance (somewhat like computed gotos in C). It would be great if re2c added this feature too, although it is currently in Zig's master branch.

**Comment by skvadrik** [comment]
I added labelled loops for Zig in https://github.com/skvadrik/re2c/commit/72a7d1b3039fe35ad7797fa7dda5042d1323314f (it hasn't been merged into `master` yet, but it will be merged soon). This feature is important for correctness, as it would be quite easy to forget about the hidden loop generated by re2c when enclosing it in an outer user-defined loop. It is possible to suppress label generation by setting `re2c:label:yyloop = "";` (e.g. if the Zig toolchain in use doesn't have this feature yet).

**Comment by Ev1lT3rm1nal** [comment]
This looks awesome! Thank you for updating the library for the upcoming changes.

**Comment by skvadrik** [comment]
@triallax It might be difficult to change, as re2c code generation is based on syntax files: the same code [generates loop/switch for all backends](https://github.com/skvadrik/re2c/blob/master/src/codegen/pass2_generate.cc#L1857) and the details for Zig are specified [in the syntax file](https://github.com/skvadrik/re2c/blob/master/include/syntax/zig#L203). The same syntax is used to render switch statements on `yych` and `yystate`.
