### ISSUE TITLE
"--emit-dot --lang haskell" Generates dot code with wrong comment syntax.

### ISSUE THREAD

**Issue by PolarGoose** [skvadrik/re2c#495]
The command:
`re2c.exe examples/haskell/01_basic.re --lang haskell -o /output.txt -i --no-version --no-generation-date`
Generates the following dot file:
```
-- Generated by re2hs
{-# LANGUAGE RecordWildCards #-}
digraph re2c {
0 -> 1 [label="[0x00-0][:-0xFF]"]
0 -> 3 [label="[1-9]"]
1 -> 2
2 [label="/input.txt:19"]
3 -> 4
4 -> 5 [label="[0x00-/][:-0xFF]"]
4 -> 3 [label="[0-9]"]
5 [label="/input.txt:18"]
}
```
The comment section in the beginning has the wrong syntax:
```
-- Generated by re2hs
{-# LANGUAGE RecordWildCards #-}
```
Dot language only understands C++ comment syntax: [Comments and optional formatting](https://graphviz.org/doc/info/lang.html#Comments%20and%20optional%20formatting)

**Comment by skvadrik** [comment]
Thanks for reporting! This should be fixed by https://github.com/skvadrik/re2c/commit/cffecf2bc5f3dc95183a2880bccab0deb1b0c1c6.
