### ISSUE TITLE
Use as a library?

### ISSUE THREAD

**Issue by stevefan1999-personal** [skvadrik/re2c#496]
I want to put this in a Rust build script so I don't have to run the generator every time. I wonder if there is a way to interface with the `re2rust` program as a library?

**Comment by skvadrik** [comment]
Not at the moment. There is [libre2c](https://github.com/skvadrik/re2c/tree/master/lib), but it exists for a different purpose (it exposes only DFA construction algorithms and does not include code generator). Can you explain your setup a bit more, e.g. why it would be a problem for the build script to call an external program? Is it not what build scripts usually do?

**Comment by stevefan1999-personal** [comment]
> Not at the moment. There is [libre2c](https://github.com/skvadrik/re2c/tree/master/lib), but it exists for a different purpose (it exposes only DFA construction algorithms and does not include code generator). Can you explain your setup a bit more, e.g. why it would be a problem for the build script to call an external program? Is it not what build scripts usually do?

Well, I can't assume the user always have re2c installed

**Comment by PolarGoose** [comment]
> Well, I can't assume the user always have re2c installed

I had a similar issue in my Cmake project. Can you download `re2c.exe` as a pre-build event and execute it for the *.re files? How is the fact that it is a library going to help? Or do you mean you want re2c to be a rust crate that you can reference?

**Comment by skvadrik** [comment]
Closing due to a lack of reply on the user side; please reopen if needed.
