### ISSUE TITLE
Cleanup, Fix warnings, allow build with bison 1.875, makerpm

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#63]
Just as a reminder here is my version that does:

\- a little clean up
- allow build with newer g++ versions and bison 1.875
(re2c should now build with all current and older g++ 
and yacc or bison versions)
- fix some warnings
- putting in cvs tags
- added a makerpm script
- added re2c --version

hope to get the changes intergrated :-)

When you apply the patch you either need to do make 
clean and remove the now missing files from cvs or do it 
manually with these files:
README
parser.cc
parser.tab.h
re2c.1
scanner.cc
version.h
y.tab.h

(the patch turns those into temp files).

The patch is against todays version (2004.01.27).

You may also want to verify your README changes to 
the new file README.in (and look out for how the 
version info is inserted there).

regards
marcus

Original comment by: helly

**Comment by linuxlovell** [comment]
thanks www.movied.org
