### ISSUE TITLE
braced quantifiers: {\d+(,|,\d+)?} style

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#64]
0.9.1 supports nongreedy * and + closure quantifiers.

This patch allows for perl-style {\d+(,|,\d+)?}
closures.  Why describe it myself, a clip from the
perlre man page:

{n}    Match exactly n times
{n,}   Match at least n times
{n,m}  Match at least n but not more than m
times

Example re2c patthen:

"a" "b"{4,8} "c" { code here; }

As with the _ and * quantifiers, it modified a a
"primary" gammar element.

Original comment by: yourjesus

**Comment by linuxlovell** [comment]
thanks www.movied.org
