### ISSUE TITLE
automake build patch

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#65]
I made a patch to get re2c built with automake. Maybe I'm not the 
only one who has been longing for a familiar "configure" build 
system in RE2C. Enjoy!

Patching instruction:

$ cd re2c (your CVS working directory)
$ patch -p1 &lt; re2c-automake-patch.diff
$ chmod 755 autogen.sh cvsclean.sh
$ ./autogen.sh

Original comment by: moriyoshi

**Comment by linuxlovell** [comment]
thanks www.movied.org
