### ISSUE TITLE
Make generated if comparisons work with characters above 127

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#66]
On writing a lexer dealing with UTF-8 characters, I
came across a problem with generated if's.  Here is a
code snippet:

if(yych &lt;= '\277'){
//blah blah
}

The above comparison always fails (at least on MSVC
2003) since '\277' is negative.  I believe it's
conformant to the C++ spec that the type of a character
literal is 'char'.

The patch changes code.cc so the above snippet becomes
if(yych &lt;= L'\277'){
//blah blah
}

In fact, it might not be a bad idea to prefix L to
every character literal generated by RE2C.

Original comment by: limethief

**Comment by linuxlovell** [comment]
thanks www.movied.org
