### ISSUE TITLE
do not generate goto next state

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#79]
This is arguably redandand as optimizers will remove
these gotos anyway, but the generated code becomes much
more readable (and maybe it'll help optimizer as well :-).

The attached patch removes gotos that were generated
from the current state to the next one, like in the
following example:

yy37:
++YYCURSOR;
if((yych = *YYCURSOR) == '=')  goto yy96;
goto yy38;

yy38:
{ RET('*'); }

Patched re2c generates instead:

yy37:
++YYCURSOR;
if((yych = *YYCURSOR) == '=') goto yy96;

{ RET('*'); }

Original comment by: alder

**Comment by linuxjackto1** [comment]
thanks www.movied.org
