### ISSUE TITLE
expose YYCTXMARKER

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#81]
In my initial patch I missed the case that YYFILL
implementation might shift in the buffer an accumulated
token and a partially accumulated trailing context. To
allow YYFILL handle such "shifts" properly we need to
expose the YYCTXMARKER in the same way we always
exposed the YYMARKER.

I attached patches for re2c and htdocs, and new ctx.re.

To test that everything still works I rerun ctx.re
(obviously) and c.re tests. The latter to ensure that
existing specs that do not use trailing context won't
be affected even though they do not define YYCTXMARKER.

Original comment by: alder

**Comment by linuxjackto1** [comment]
thanks www.movied.org
