### ISSUE TITLE
Windows support (takes only a few minutes)

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#90]
Hi!
I have just started using re2c on windows and therefore 
I needed to make a few changes to create a running 
version. As I don't know how to use CVS I would be glad 
if you applied the following changes to the source:

\- Use istream (ifstream or cin) instead of unix 
open/read/close
- Rename the .cc files to .cpp (makes compiling on 
windows easier, but that's not neccessary)

I appended "my version" of re2c, but I'm not sure 
whether this is the newest version because I didn't get 
it via CVS but by the sourceforge download page.

Thanks a lot,
Jakob

Original comment by: *anonymous

**Comment by linuxlovell** [comment]
thanks www.movied.org
