### ISSUE TITLE
Transparent handling of #line directives in input files

### ISSUE THREAD

**Issue by skvadrik** [skvadrik/re2c#98]
I was playing around with a project where I pass the re2c input file through a preprocessor (m4) first. For best results in this situation, it's best if re2c can handle #file directives in its input file.

The attached patch to 0.13.3 accomplishes this. While it takes reasonable precautions against false matches for #line directives, it does not strictly check for the directives to start at the beginning of a line (as far as I know, re2c does not yet support the ^pattern syntax, does it?)

While I tried to match the general style of re2c's source code, I'm open to reworking the patch to meet any further standards I may have missed.

Original comment by: neeri

**Comment by pskocik** [comment]
This doesn't appear to be working. I tried to use lemon output (with #line directives) as re2c input and large parts of the generated source got deleted. If I try feeding the output of running re2c on

	typedef enum num_t { ERR, BIN, OCT, DEC, HEX } num_t;
	static num_t lex(const char *YYCURSOR)
	{
		const char *YYMARKER;
		/*!re2c
			re2c:define:YYCTYPE = char;
			re2c:yyfill:enable = 0;

			end = "\x00";
			bin = '0b' [01]+;
			oct = "0" [0-7]*;
			dec = [1-9][0-9]*;
			hex = '0x' [0-9a-fA-F]+;

			*       { return ERR; }
			bin end { return BIN; }
			oct end { return OCT; }
			dec end { return DEC; }
			hex end { return HEX; }
		*/
	}

(from the docs) back to re2c with 

re2c example.c.re  |re2c -

I get

/* Generated by re2c 1.0.3 on Mon Jun 25 20:48:07 2018 */
#line 1 "<stdin>"

	}

(I'm on an older browser and I'm having some difficulties with the commenting tool, so apologies for the formatting.)
